%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10139').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10139.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10139001') ->
    #'Proto10139001'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139002') ->
    #'Proto10139002'{'task_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task_id'}	% task_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139003') ->
    #'Proto10139003'{'main_type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='main_type'}	% main_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139004') ->
    #'Proto10139004'{'main_type'=F1,'task_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='main_type'},	% main_type
        #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F2,field_name='task_id'}	% task_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139006') ->
    #'Proto10139006'{'task_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task_id'}	% task_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139007') ->
    #'Proto10139007'{'task_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task_id'}	% task_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139008') ->
    #'Proto10139008'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139009') ->
    #'Proto10139009'{'task_id'=F1,'amount'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task_id'},	% task_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='amount'}	% amount
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139010') ->
    #'Proto10139010'{'is_free'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='is_free'}	% is_free
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10139011') ->
    #'Proto10139011'{'task_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task_id'}	% task_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50139001') ->
    #'Proto50139001'{'task_list'=F1,'type'=F2,'government'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTaskInfo',is_array=1,value=F1,field_name='task_list'},	% task_list
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoGovernmentDetail',is_array=0,value=F3,field_name='government'}	% government
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50139003') ->
    #'Proto50139003'{'task'=F1,'main_type'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=0,value=F1,field_name='task'},	% task
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='main_type'}	% main_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50139004') ->
    #'Proto50139004'{'task'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=0,value=F1,field_name='task'}	% task
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80139001') ->
    #'Proto80139001'{'task'=F1,'cmd'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTaskInfo',is_array=0,value=F1,field_name='task'},	% task
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='cmd'}	% cmd
    ].
fetch_field_map('Proto10139001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10139002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task_id'}	% task_id
    };
fetch_field_map('Proto10139003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='main_type'}	% main_type
    };
fetch_field_map('Proto10139004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='main_type'},	% main_type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='task_id'}	% task_id
    };
fetch_field_map('Proto10139006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task_id'}	% task_id
    };
fetch_field_map('Proto10139007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task_id'}	% task_id
    };
fetch_field_map('Proto10139008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10139009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task_id'},	% task_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='amount'}	% amount
    };
fetch_field_map('Proto10139010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_free'}	% is_free
    };
fetch_field_map('Proto10139011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task_id'}	% task_id
    };
fetch_field_map('Proto50139001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTaskInfo',is_array=1,field_name='task_list'},	% task_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoGovernmentDetail',is_array=0,field_name='government'}	% government
    };
fetch_field_map('Proto50139003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=0,field_name='task'},	% task
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='main_type'}	% main_type
    };
fetch_field_map('Proto50139004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=0,field_name='task'}	% task
    };
fetch_field_map('Proto80139001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTaskInfo',is_array=0,field_name='task'},	% task
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='cmd'}	% cmd
    }.
field_map_to_msg('Proto10139001', FieldMap) ->
    #'Proto10139001'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139002', FieldMap) ->
    #'Proto10139002'{
        'task_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139003', FieldMap) ->
    #'Proto10139003'{
        'main_type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139004', FieldMap) ->
    #'Proto10139004'{
        'main_type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'task_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10139006', FieldMap) ->
    #'Proto10139006'{
        'task_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139007', FieldMap) ->
    #'Proto10139007'{
        'task_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139008', FieldMap) ->
    #'Proto10139008'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139009', FieldMap) ->
    #'Proto10139009'{
        'task_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'amount' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10139010', FieldMap) ->
    #'Proto10139010'{
        'is_free' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10139011', FieldMap) ->
    #'Proto10139011'{
        'task_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50139001', FieldMap) ->
    #'Proto50139001'{
        'task_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'government' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50139003', FieldMap) ->
    #'Proto50139003'{
        'task' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'main_type' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50139004', FieldMap) ->
    #'Proto50139004'{
        'task' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80139001', FieldMap) ->
    #'Proto80139001'{
        'task' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'cmd' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
