%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10128').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10128.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10128001') ->
    #'Proto10128001'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128002') ->
    #'Proto50128002'{'notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='notice'}	% notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128002') ->
    #'Proto10128002'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128012') ->
    #'Proto10128012'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128006') ->
    #'Proto10128006'{'player_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'}	% player_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128021') ->
    #'Proto10128021'{'type'=F1,'page'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='page'}	% page
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128202') ->
    #'Proto50128202'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128011') ->
    #'Proto10128011'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128014') ->
    #'Proto10128014'{'player_id'=F1,'city_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'},	% player_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128008') ->
    #'Proto10128008'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128101') ->
    #'Proto50128101'{'result'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='result'}	% result
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128021') ->
    #'Proto50128021'{'type'=F1,'page'=F2,'max_page'=F3,'rank_list'=F4,'self_rank'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='page'},	% page
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='max_page'},	% max_page
        #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoCountryRanker',is_array=1,value=F4,field_name='rank_list'},	% rank_list
        #proto_field{field_tag=5,wire_type=2,data_type=16,data_type_name='ProtoCountryRanker',is_array=0,value=F5,field_name='self_rank'}	% self_rank
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128011') ->
    #'Proto50128011'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128008') ->
    #'Proto50128008'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128201') ->
    #'Proto50128201'{'task'=F1,'param'=F2,'current'=F3,'target'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='task'},	% task
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=1,value=F2,field_name='param'},	% param
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='current'},	% current
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='target'}	% target
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128001') ->
    #'Proto50128001'{'player_list'=F1,'is_in_impeach'=F2,'king_change_tick'=F3,'city_number'=F4,'can_impeach'=F5,'can_impeach_votes'=F6,'cur_stage'=F7,'max_stage'=F8}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryPlayer',is_array=1,value=F1,field_name='player_list'},	% player_list
        #proto_field{field_tag=2,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F2,field_name='is_in_impeach'},	% is_in_impeach
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='king_change_tick'},	% king_change_tick
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='city_number'},	% city_number
        #proto_field{field_tag=5,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F5,field_name='can_impeach'},	% can_impeach
        #proto_field{field_tag=6,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F6,field_name='can_impeach_votes'},	% can_impeach_votes
        #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F7,field_name='cur_stage'},	% cur_stage
        #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F8,field_name='max_stage'}	% max_stage
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128102') ->
    #'Proto50128102'{'red_packet_num'=F1,'year_annihilation'=F2,'year_battle_losses'=F3,'year_construction_values'=F4,'quarter_gold'=F5,'quarter_silver'=F6,'quarter_cereals'=F7,'gold_repertory'=F8,'silver_repertory'=F9,'cereals_repertory'=F10,'recharge_list'=F11,'box_level'=F12}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='red_packet_num'},	% red_packet_num
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='year_annihilation'},	% year_annihilation
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='year_battle_losses'},	% year_battle_losses
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='year_construction_values'},	% year_construction_values
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='quarter_gold'},	% quarter_gold
        #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F6,field_name='quarter_silver'},	% quarter_silver
        #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F7,field_name='quarter_cereals'},	% quarter_cereals
        #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F8,field_name='gold_repertory'},	% gold_repertory
        #proto_field{field_tag=9,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F9,field_name='silver_repertory'},	% silver_repertory
        #proto_field{field_tag=10,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F10,field_name='cereals_repertory'},	% cereals_repertory
        #proto_field{field_tag=11,wire_type=2,data_type=16,data_type_name='ProtoRechargeDividends',is_array=1,value=F11,field_name='recharge_list'},	% recharge_list
        #proto_field{field_tag=12,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F12,field_name='box_level'}	% box_level
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128009') ->
    #'Proto10128009'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128009') ->
    #'Proto50128009'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80128003') ->
    #'Proto80128003'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128015') ->
    #'Proto50128015'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128013') ->
    #'Proto50128013'{'city_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCity',is_array=1,value=F1,field_name='city_list'}	% city_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128007') ->
    #'Proto10128007'{'player_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'}	% player_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128004') ->
    #'Proto50128004'{'player_id'=F1,'pos'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'},	% player_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='pos'}	% pos
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128003') ->
    #'Proto10128003'{'notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='notice'}	% notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128015') ->
    #'Proto10128015'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128010') ->
    #'Proto10128010'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128014') ->
    #'Proto50128014'{'player_id'=F1,'city_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'},	% player_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128005') ->
    #'Proto50128005'{'player_a'=F1,'player_b'=F2,'a_number'=F3,'b_number'=F4,'is_in_impeach'=F5,'start_tick'=F6,'is_votes'=F7}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,value=F1,field_name='player_a'},	% player_a
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,value=F2,field_name='player_b'},	% player_b
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='a_number'},	% a_number
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='b_number'},	% b_number
        #proto_field{field_tag=5,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F5,field_name='is_in_impeach'},	% is_in_impeach
        #proto_field{field_tag=6,wire_type=0,data_type=3,data_type_name='undefined',is_array=0,value=F6,field_name='start_tick'},	% start_tick
        #proto_field{field_tag=7,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F7,field_name='is_votes'}	% is_votes
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128003') ->
    #'Proto50128003'{'notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='notice'}	% notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128101') ->
    #'Proto10128101'{'num'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='num'}	% num
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128007') ->
    #'Proto50128007'{'player_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'}	% player_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80128004') ->
    #'Proto80128004'{'order_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryOrder',is_array=1,value=F1,field_name='order_list'}	% order_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128016') ->
    #'Proto10128016'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128005') ->
    #'Proto10128005'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128016') ->
    #'Proto50128016'{'order_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryOrder',is_array=1,value=F1,field_name='order_list'}	% order_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128006') ->
    #'Proto50128006'{'player_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'}	% player_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128013') ->
    #'Proto10128013'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128012') ->
    #'Proto50128012'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80128001') ->
    #'Proto80128001'{'notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='notice'}	% notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10128004') ->
    #'Proto10128004'{'player_id'=F1,'pos'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'},	% player_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='pos'}	% pos
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50128010') ->
    #'Proto50128010'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80128002') ->
    #'Proto80128002'{'pos'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='pos'}	% pos
    ].
fetch_field_map('Proto10128001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50128002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='notice'}	% notice
    };
fetch_field_map('Proto10128002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10128012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10128006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'}	% player_id
    };
fetch_field_map('Proto10128021') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='page'}	% page
    };
fetch_field_map('Proto50128202') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto10128011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10128014') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'},	% player_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10128008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128101') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='result'}	% result
    };
fetch_field_map('Proto50128021') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='page'},	% page
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='max_page'},	% max_page
        4 => #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoCountryRanker',is_array=1,field_name='rank_list'},	% rank_list
        5 => #proto_field{field_tag=5,wire_type=2,data_type=16,data_type_name='ProtoCountryRanker',is_array=0,field_name='self_rank'}	% self_rank
    };
fetch_field_map('Proto50128011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50128008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128201') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='task'},	% task
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoCountryTask',is_array=1,field_name='param'},	% param
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='current'},	% current
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='target'}	% target
    };
fetch_field_map('Proto50128001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryPlayer',is_array=1,field_name='player_list'},	% player_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_in_impeach'},	% is_in_impeach
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='king_change_tick'},	% king_change_tick
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_number'},	% city_number
        5 => #proto_field{field_tag=5,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='can_impeach'},	% can_impeach
        6 => #proto_field{field_tag=6,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='can_impeach_votes'},	% can_impeach_votes
        7 => #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='cur_stage'},	% cur_stage
        8 => #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='max_stage'}	% max_stage
    };
fetch_field_map('Proto50128102') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='red_packet_num'},	% red_packet_num
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='year_annihilation'},	% year_annihilation
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='year_battle_losses'},	% year_battle_losses
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='year_construction_values'},	% year_construction_values
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='quarter_gold'},	% quarter_gold
        6 => #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='quarter_silver'},	% quarter_silver
        7 => #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='quarter_cereals'},	% quarter_cereals
        8 => #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='gold_repertory'},	% gold_repertory
        9 => #proto_field{field_tag=9,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='silver_repertory'},	% silver_repertory
        10 => #proto_field{field_tag=10,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='cereals_repertory'},	% cereals_repertory
        11 => #proto_field{field_tag=11,wire_type=2,data_type=16,data_type_name='ProtoRechargeDividends',is_array=1,field_name='recharge_list'},	% recharge_list
        12 => #proto_field{field_tag=12,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='box_level'}	% box_level
    };
fetch_field_map('Proto10128009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto80128003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128015') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128013') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCity',is_array=1,field_name='city_list'}	% city_list
    };
fetch_field_map('Proto10128007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'}	% player_id
    };
fetch_field_map('Proto50128004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'},	% player_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='pos'}	% pos
    };
fetch_field_map('Proto10128003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='notice'}	% notice
    };
fetch_field_map('Proto10128015') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10128010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50128014') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'},	% player_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50128005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,field_name='player_a'},	% player_a
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,field_name='player_b'},	% player_b
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='a_number'},	% a_number
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='b_number'},	% b_number
        5 => #proto_field{field_tag=5,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_in_impeach'},	% is_in_impeach
        6 => #proto_field{field_tag=6,wire_type=0,data_type=3,data_type_name='undefined',is_array=0,field_name='start_tick'},	% start_tick
        7 => #proto_field{field_tag=7,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_votes'}	% is_votes
    };
fetch_field_map('Proto50128003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='notice'}	% notice
    };
fetch_field_map('Proto10128101') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='num'}	% num
    };
fetch_field_map('Proto50128007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'}	% player_id
    };
fetch_field_map('Proto80128004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryOrder',is_array=1,field_name='order_list'}	% order_list
    };
fetch_field_map('Proto10128016') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10128005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50128016') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCountryOrder',is_array=1,field_name='order_list'}	% order_list
    };
fetch_field_map('Proto50128006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'}	% player_id
    };
fetch_field_map('Proto10128013') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50128012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto80128001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='notice'}	% notice
    };
fetch_field_map('Proto10128004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'},	% player_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='pos'}	% pos
    };
fetch_field_map('Proto50128010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto80128002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='pos'}	% pos
    }.
field_map_to_msg('Proto10128001', FieldMap) ->
    #'Proto10128001'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128002', FieldMap) ->
    #'Proto50128002'{
        'notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128002', FieldMap) ->
    #'Proto10128002'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128012', FieldMap) ->
    #'Proto10128012'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128006', FieldMap) ->
    #'Proto10128006'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128021', FieldMap) ->
    #'Proto10128021'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'page' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50128202', FieldMap) ->
    #'Proto50128202'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128011', FieldMap) ->
    #'Proto10128011'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128014', FieldMap) ->
    #'Proto10128014'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'city_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10128008', FieldMap) ->
    #'Proto10128008'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128101', FieldMap) ->
    #'Proto50128101'{
        'result' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128021', FieldMap) ->
    #'Proto50128021'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'page' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'max_page' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'rank_list' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'self_rank' = gb_unserialize:get_value(maps:get(5,FieldMap))
    };
field_map_to_msg('Proto50128011', FieldMap) ->
    #'Proto50128011'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128008', FieldMap) ->
    #'Proto50128008'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128201', FieldMap) ->
    #'Proto50128201'{
        'task' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'param' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'current' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'target' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50128001', FieldMap) ->
    #'Proto50128001'{
        'player_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'is_in_impeach' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'king_change_tick' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'city_number' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'can_impeach' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'can_impeach_votes' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'cur_stage' = gb_unserialize:get_value(maps:get(7,FieldMap)),
        'max_stage' = gb_unserialize:get_value(maps:get(8,FieldMap))
    };
field_map_to_msg('Proto50128102', FieldMap) ->
    #'Proto50128102'{
        'red_packet_num' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'year_annihilation' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'year_battle_losses' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'year_construction_values' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'quarter_gold' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'quarter_silver' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'quarter_cereals' = gb_unserialize:get_value(maps:get(7,FieldMap)),
        'gold_repertory' = gb_unserialize:get_value(maps:get(8,FieldMap)),
        'silver_repertory' = gb_unserialize:get_value(maps:get(9,FieldMap)),
        'cereals_repertory' = gb_unserialize:get_value(maps:get(10,FieldMap)),
        'recharge_list' = gb_unserialize:get_value(maps:get(11,FieldMap)),
        'box_level' = gb_unserialize:get_value(maps:get(12,FieldMap))
    };
field_map_to_msg('Proto10128009', FieldMap) ->
    #'Proto10128009'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128009', FieldMap) ->
    #'Proto50128009'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80128003', FieldMap) ->
    #'Proto80128003'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128015', FieldMap) ->
    #'Proto50128015'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128013', FieldMap) ->
    #'Proto50128013'{
        'city_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128007', FieldMap) ->
    #'Proto10128007'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128004', FieldMap) ->
    #'Proto50128004'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'pos' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10128003', FieldMap) ->
    #'Proto10128003'{
        'notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128015', FieldMap) ->
    #'Proto10128015'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128010', FieldMap) ->
    #'Proto10128010'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128014', FieldMap) ->
    #'Proto50128014'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'city_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50128005', FieldMap) ->
    #'Proto50128005'{
        'player_a' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'player_b' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'a_number' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'b_number' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'is_in_impeach' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'start_tick' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'is_votes' = gb_unserialize:get_value(maps:get(7,FieldMap))
    };
field_map_to_msg('Proto50128003', FieldMap) ->
    #'Proto50128003'{
        'notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128101', FieldMap) ->
    #'Proto10128101'{
        'num' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128007', FieldMap) ->
    #'Proto50128007'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80128004', FieldMap) ->
    #'Proto80128004'{
        'order_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128016', FieldMap) ->
    #'Proto10128016'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128005', FieldMap) ->
    #'Proto10128005'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128016', FieldMap) ->
    #'Proto50128016'{
        'order_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128006', FieldMap) ->
    #'Proto50128006'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128013', FieldMap) ->
    #'Proto10128013'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50128012', FieldMap) ->
    #'Proto50128012'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80128001', FieldMap) ->
    #'Proto80128001'{
        'notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10128004', FieldMap) ->
    #'Proto10128004'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'pos' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50128010', FieldMap) ->
    #'Proto50128010'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80128002', FieldMap) ->
    #'Proto80128002'{
        'pos' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
