%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10130').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10130.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10130002') ->
    #'Proto10130002'{'type'=F1,'use_type'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='use_type'}	% use_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50130001') ->
    #'Proto50130001'{'remaining_free_times'=F1,'all_times'=F2,'buy_times'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='remaining_free_times'},	% remaining_free_times
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='all_times'},	% all_times
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F3,field_name='buy_times'}	% buy_times
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50130002') ->
    #'Proto50130002'{'remaining_free_times'=F1,'all_times'=F2,'buy_times'=F3,'is_cruel'=F4,'item'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='remaining_free_times'},	% remaining_free_times
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='all_times'},	% all_times
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F3,field_name='buy_times'},	% buy_times
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='is_cruel'},	% is_cruel
        #proto_field{field_tag=5,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F5,field_name='item'}	% item
    ].
fetch_field_map('Proto10130002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='use_type'}	% use_type
    };
fetch_field_map('Proto50130001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='remaining_free_times'},	% remaining_free_times
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='all_times'},	% all_times
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='buy_times'}	% buy_times
    };
fetch_field_map('Proto50130002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='remaining_free_times'},	% remaining_free_times
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='all_times'},	% all_times
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='buy_times'},	% buy_times
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_cruel'},	% is_cruel
        5 => #proto_field{field_tag=5,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item'}	% item
    }.
field_map_to_msg('Proto10130002', FieldMap) ->
    #'Proto10130002'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'use_type' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50130001', FieldMap) ->
    #'Proto50130001'{
        'remaining_free_times' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'all_times' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'buy_times' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50130002', FieldMap) ->
    #'Proto50130002'{
        'remaining_free_times' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'all_times' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'buy_times' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'is_cruel' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'item' = gb_unserialize:get_value(maps:get(5,FieldMap))
    }.
