%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10146').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10146.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10146001') ->
    #'Proto10146001'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10146002') ->
    #'Proto10146002'{'city_id'=F1,'is_free'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'},	% city_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='is_free'}	% is_free
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10146003') ->
    #'Proto10146003'{'type'=F1,'city_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10146004') ->
    #'Proto10146004'{'city_id'=F1,'hero_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'},	% city_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='hero_id'}	% hero_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10146005') ->
    #'Proto10146005'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50146001') ->
    #'Proto50146001'{'city_id'=F1,'robot_id'=F2,'times'=F3,'left_times'=F4,'is_lock'=F5,'refresh_time_tick'=F6,'is_max_free_refresh_times'=F7,'item_list'=F8,'predict'=F9,'hero_base'=F10}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'},	% city_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='robot_id'},	% robot_id
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='times'},	% times
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='left_times'},	% left_times
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='is_lock'},	% is_lock
        #proto_field{field_tag=6,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F6,field_name='refresh_time_tick'},	% refresh_time_tick
        #proto_field{field_tag=7,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F7,field_name='is_max_free_refresh_times'},	% is_max_free_refresh_times
        #proto_field{field_tag=8,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F8,field_name='item_list'},	% item_list
        #proto_field{field_tag=9,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F9,field_name='predict'},	% predict
        #proto_field{field_tag=10,wire_type=2,data_type=16,data_type_name='ProtoHeroBase',is_array=0,value=F10,field_name='hero_base'}	% hero_base
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80146001') ->
    #'Proto80146001'{'puppet_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F1,field_name='puppet_list'}	% puppet_list
    ].
fetch_field_map('Proto10146001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10146002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'},	% city_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_free'}	% is_free
    };
fetch_field_map('Proto10146003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10146004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'},	% city_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'}	% hero_id
    };
fetch_field_map('Proto10146005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50146001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'},	% city_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='robot_id'},	% robot_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='times'},	% times
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='left_times'},	% left_times
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_lock'},	% is_lock
        6 => #proto_field{field_tag=6,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='refresh_time_tick'},	% refresh_time_tick
        7 => #proto_field{field_tag=7,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_max_free_refresh_times'},	% is_max_free_refresh_times
        8 => #proto_field{field_tag=8,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'},	% item_list
        9 => #proto_field{field_tag=9,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='predict'},	% predict
        10 => #proto_field{field_tag=10,wire_type=2,data_type=16,data_type_name='ProtoHeroBase',is_array=0,field_name='hero_base'}	% hero_base
    };
fetch_field_map('Proto80146001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='puppet_list'}	% puppet_list
    }.
field_map_to_msg('Proto10146001', FieldMap) ->
    #'Proto10146001'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10146002', FieldMap) ->
    #'Proto10146002'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'is_free' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10146003', FieldMap) ->
    #'Proto10146003'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'city_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10146004', FieldMap) ->
    #'Proto10146004'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10146005', FieldMap) ->
    #'Proto10146005'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50146001', FieldMap) ->
    #'Proto50146001'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'robot_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'times' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'left_times' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'is_lock' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'refresh_time_tick' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'is_max_free_refresh_times' = gb_unserialize:get_value(maps:get(7,FieldMap)),
        'item_list' = gb_unserialize:get_value(maps:get(8,FieldMap)),
        'predict' = gb_unserialize:get_value(maps:get(9,FieldMap)),
        'hero_base' = gb_unserialize:get_value(maps:get(10,FieldMap))
    };
field_map_to_msg('Proto80146001', FieldMap) ->
    #'Proto80146001'{
        'puppet_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
