%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10100').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10100.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10100001') ->
    #'Proto10100001'{'account'=F1,'tick'=F2,'session'=F3,'server_flag'=F4,'server_name'=F5,'agent'=F6,'market'=F7,'net_type'=F8,'sys_version'=F9,'sys_model'=F10,'mac'=F11,'client_type'=F12,'area'=F13,'sdk_sid'=F14,'msg_tocken'=F15,'device'=F16}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='account'},	% account
        #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F2,field_name='tick'},	% tick
        #proto_field{field_tag=3,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F3,field_name='session'},	% session
        #proto_field{field_tag=4,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F4,field_name='server_flag'},	% server_flag
        #proto_field{field_tag=5,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F5,field_name='server_name'},	% server_name
        #proto_field{field_tag=6,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F6,field_name='agent'},	% agent
        #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F7,field_name='market'},	% market
        #proto_field{field_tag=8,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F8,field_name='net_type'},	% net_type
        #proto_field{field_tag=9,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F9,field_name='sys_version'},	% sys_version
        #proto_field{field_tag=10,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F10,field_name='sys_model'},	% sys_model
        #proto_field{field_tag=11,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F11,field_name='mac'},	% mac
        #proto_field{field_tag=12,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F12,field_name='client_type'},	% client_type
        #proto_field{field_tag=13,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F13,field_name='area'},	% area
        #proto_field{field_tag=14,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F14,field_name='sdk_sid'},	% sdk_sid
        #proto_field{field_tag=15,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F15,field_name='msg_tocken'},	% msg_tocken
        #proto_field{field_tag=16,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F16,field_name='device'}	% device
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10100002') ->
    #'Proto10100002'{'sex'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='sex'}	% sex
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10100003') ->
    #'Proto10100003'{'role_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='role_id'}	% role_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10100004') ->
    #'Proto10100004'{'country'=F1,'name'=F2,'sex'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='country'},	% country
        #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F2,field_name='name'},	% name
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='sex'}	% sex
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10100007') ->
    #'Proto10100007'{'role_id'=F1,'session'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='role_id'},	% role_id
        #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F2,field_name='session'}	% session
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10100099') ->
    #'Proto10100099'{'test12'=F1,'df4er4489972'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='test12'},	% test12
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='df4er4489972'}	% df4er4489972
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100001') ->
    #'Proto50100001'{'role_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoGateRole',is_array=1,value=F1,field_name='role_list'}	% role_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100002') ->
    #'Proto50100002'{'name'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='name'}	% name
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100004') ->
    #'Proto50100004'{'role_id'=F1,'role_name'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='role_id'},	% role_id
        #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F2,field_name='role_name'}	% role_name
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100005') ->
    #'Proto50100005'{'time'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='time'}	% time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100006') ->
    #'Proto50100006'{'info'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoPairLong',is_array=1,value=F1,field_name='info'}	% info
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50100008') ->
    #'Proto50100008'{'tick'=F1,'val'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='tick'},	% tick
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='val'}	% val
    ].
fetch_field_map('Proto10100001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='account'},	% account
        2 => #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='tick'},	% tick
        3 => #proto_field{field_tag=3,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='session'},	% session
        4 => #proto_field{field_tag=4,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='server_flag'},	% server_flag
        5 => #proto_field{field_tag=5,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='server_name'},	% server_name
        6 => #proto_field{field_tag=6,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='agent'},	% agent
        7 => #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='market'},	% market
        8 => #proto_field{field_tag=8,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='net_type'},	% net_type
        9 => #proto_field{field_tag=9,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='sys_version'},	% sys_version
        10 => #proto_field{field_tag=10,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='sys_model'},	% sys_model
        11 => #proto_field{field_tag=11,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='mac'},	% mac
        12 => #proto_field{field_tag=12,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='client_type'},	% client_type
        13 => #proto_field{field_tag=13,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='area'},	% area
        14 => #proto_field{field_tag=14,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='sdk_sid'},	% sdk_sid
        15 => #proto_field{field_tag=15,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='msg_tocken'},	% msg_tocken
        16 => #proto_field{field_tag=16,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='device'}	% device
    };
fetch_field_map('Proto10100002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='sex'}	% sex
    };
fetch_field_map('Proto10100003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='role_id'}	% role_id
    };
fetch_field_map('Proto10100004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='country'},	% country
        2 => #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='name'},	% name
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='sex'}	% sex
    };
fetch_field_map('Proto10100007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='role_id'},	% role_id
        2 => #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='session'}	% session
    };
fetch_field_map('Proto10100099') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='test12'},	% test12
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='df4er4489972'}	% df4er4489972
    };
fetch_field_map('Proto50100001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoGateRole',is_array=1,field_name='role_list'}	% role_list
    };
fetch_field_map('Proto50100002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='name'}	% name
    };
fetch_field_map('Proto50100004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='role_id'},	% role_id
        2 => #proto_field{field_tag=2,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='role_name'}	% role_name
    };
fetch_field_map('Proto50100005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='time'}	% time
    };
fetch_field_map('Proto50100006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoPairLong',is_array=1,field_name='info'}	% info
    };
fetch_field_map('Proto50100008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='tick'},	% tick
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='val'}	% val
    }.
field_map_to_msg('Proto10100001', FieldMap) ->
    #'Proto10100001'{
        'account' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'tick' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'session' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'server_flag' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'server_name' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'agent' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'market' = gb_unserialize:get_value(maps:get(7,FieldMap)),
        'net_type' = gb_unserialize:get_value(maps:get(8,FieldMap)),
        'sys_version' = gb_unserialize:get_value(maps:get(9,FieldMap)),
        'sys_model' = gb_unserialize:get_value(maps:get(10,FieldMap)),
        'mac' = gb_unserialize:get_value(maps:get(11,FieldMap)),
        'client_type' = gb_unserialize:get_value(maps:get(12,FieldMap)),
        'area' = gb_unserialize:get_value(maps:get(13,FieldMap)),
        'sdk_sid' = gb_unserialize:get_value(maps:get(14,FieldMap)),
        'msg_tocken' = gb_unserialize:get_value(maps:get(15,FieldMap)),
        'device' = gb_unserialize:get_value(maps:get(16,FieldMap))
    };
field_map_to_msg('Proto10100002', FieldMap) ->
    #'Proto10100002'{
        'sex' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10100003', FieldMap) ->
    #'Proto10100003'{
        'role_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10100004', FieldMap) ->
    #'Proto10100004'{
        'country' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'name' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'sex' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto10100007', FieldMap) ->
    #'Proto10100007'{
        'role_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'session' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10100099', FieldMap) ->
    #'Proto10100099'{
        'test12' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'df4er4489972' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50100001', FieldMap) ->
    #'Proto50100001'{
        'role_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50100002', FieldMap) ->
    #'Proto50100002'{
        'name' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50100004', FieldMap) ->
    #'Proto50100004'{
        'role_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'role_name' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50100005', FieldMap) ->
    #'Proto50100005'{
        'time' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50100006', FieldMap) ->
    #'Proto50100006'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50100008', FieldMap) ->
    #'Proto50100008'{
        'tick' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'val' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
