%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10101').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10101.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto80101001') ->
    #'Proto80101001'{'show'=F1,'exp'=F2,'open_days'=F3,'create_days'=F4,'create_tick'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,value=F1,field_name='show'},	% show
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='exp'},	% exp
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='open_days'},	% open_days
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='create_days'},	% create_days
        #proto_field{field_tag=5,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F5,field_name='create_tick'}	% create_tick
    ].
fetch_field_map('Proto80101001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,field_name='show'},	% show
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='exp'},	% exp
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='open_days'},	% open_days
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='create_days'},	% create_days
        5 => #proto_field{field_tag=5,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='create_tick'}	% create_tick
    }.
field_map_to_msg('Proto80101001', FieldMap) ->
    #'Proto80101001'{
        'show' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'exp' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'open_days' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'create_days' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'create_tick' = gb_unserialize:get_value(maps:get(5,FieldMap))
    }.
