%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10137').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10137.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10137001') ->
    #'Proto10137001'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137002') ->
    #'Proto10137002'{'type'=F1,'hero_list'=F2,'index'=F3,'tag_id'=F4,'tag_rank'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F2,field_name='hero_list'},	% hero_list
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='index'},	% index
        #proto_field{field_tag=4,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F4,field_name='tag_id'},	% tag_id
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='tag_rank'}	% tag_rank
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137003') ->
    #'Proto10137003'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137004') ->
    #'Proto10137004'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137005') ->
    #'Proto10137005'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137006') ->
    #'Proto10137006'{'page'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='page'}	% page
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10137007') ->
    #'Proto10137007'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137001') ->
    #'Proto50137001'{'country_top'=F1,'challenge_list'=F2,'self_rank'=F3,'buy_times'=F4,'used_times'=F5,'self'=F6}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,value=F1,field_name='country_top'},	% country_top
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,value=F2,field_name='challenge_list'},	% challenge_list
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='self_rank'},	% self_rank
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='buy_times'},	% buy_times
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='used_times'},	% used_times
        #proto_field{field_tag=6,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=0,value=F6,field_name='self'}	% self
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137002') ->
    #'Proto50137002'{'type'=F1,'hero_list'=F2,'index'=F3,'tag_id'=F4,'tag_rank'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F2,field_name='hero_list'},	% hero_list
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='index'},	% index
        #proto_field{field_tag=4,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F4,field_name='tag_id'},	% tag_id
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='tag_rank'}	% tag_rank
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137003') ->
    #'Proto50137003'{'buy_times'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='buy_times'}	% buy_times
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137004') ->
    #'Proto50137004'{'player_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,value=F1,field_name='player_list'}	% player_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137005') ->
    #'Proto50137005'{'record_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaRecord',is_array=1,value=F1,field_name='record_list'}	% record_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137006') ->
    #'Proto50137006'{'page'=F1,'max_page'=F2,'rank_list'=F3,'self_rank'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='page'},	% page
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='max_page'},	% max_page
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,value=F3,field_name='rank_list'},	% rank_list
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='self_rank'}	% self_rank
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50137007') ->
    #'Proto50137007'{'buy_times'=F1,'used_times'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='buy_times'},	% buy_times
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='used_times'}	% used_times
    ].
fetch_field_map('Proto10137001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10137002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'},	% hero_list
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        4 => #proto_field{field_tag=4,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='tag_id'},	% tag_id
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='tag_rank'}	% tag_rank
    };
fetch_field_map('Proto10137003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10137004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10137005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10137006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='page'}	% page
    };
fetch_field_map('Proto10137007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50137001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,field_name='country_top'},	% country_top
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,field_name='challenge_list'},	% challenge_list
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='self_rank'},	% self_rank
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='buy_times'},	% buy_times
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='used_times'},	% used_times
        6 => #proto_field{field_tag=6,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=0,field_name='self'}	% self
    };
fetch_field_map('Proto50137002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'},	% hero_list
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        4 => #proto_field{field_tag=4,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='tag_id'},	% tag_id
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='tag_rank'}	% tag_rank
    };
fetch_field_map('Proto50137003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='buy_times'}	% buy_times
    };
fetch_field_map('Proto50137004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,field_name='player_list'}	% player_list
    };
fetch_field_map('Proto50137005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoArenaRecord',is_array=1,field_name='record_list'}	% record_list
    };
fetch_field_map('Proto50137006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='page'},	% page
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='max_page'},	% max_page
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoArenaPlayer',is_array=1,field_name='rank_list'},	% rank_list
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='self_rank'}	% self_rank
    };
fetch_field_map('Proto50137007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='buy_times'},	% buy_times
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='used_times'}	% used_times
    }.
field_map_to_msg('Proto10137001', FieldMap) ->
    #'Proto10137001'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10137002', FieldMap) ->
    #'Proto10137002'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_list' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'tag_id' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'tag_rank' = gb_unserialize:get_value(maps:get(5,FieldMap))
    };
field_map_to_msg('Proto10137003', FieldMap) ->
    #'Proto10137003'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10137004', FieldMap) ->
    #'Proto10137004'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10137005', FieldMap) ->
    #'Proto10137005'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10137006', FieldMap) ->
    #'Proto10137006'{
        'page' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10137007', FieldMap) ->
    #'Proto10137007'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50137001', FieldMap) ->
    #'Proto50137001'{
        'country_top' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'challenge_list' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'self_rank' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'buy_times' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'used_times' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'self' = gb_unserialize:get_value(maps:get(6,FieldMap))
    };
field_map_to_msg('Proto50137002', FieldMap) ->
    #'Proto50137002'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_list' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'tag_id' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'tag_rank' = gb_unserialize:get_value(maps:get(5,FieldMap))
    };
field_map_to_msg('Proto50137003', FieldMap) ->
    #'Proto50137003'{
        'buy_times' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50137004', FieldMap) ->
    #'Proto50137004'{
        'player_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50137005', FieldMap) ->
    #'Proto50137005'{
        'record_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50137006', FieldMap) ->
    #'Proto50137006'{
        'page' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'max_page' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'rank_list' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'self_rank' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50137007', FieldMap) ->
    #'Proto50137007'{
        'buy_times' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'used_times' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
