%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10122').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10122.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto50122001') ->
    #'Proto50122001'{'season'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='season'}	% season
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50122002') ->
    #'Proto50122002'{'season'=F1,'day'=F2,'word_season'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='season'},	% season
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='day'},	% day
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='word_season'}	% word_season
    ].
fetch_field_map('Proto50122001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='season'}	% season
    };
fetch_field_map('Proto50122002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='season'},	% season
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='day'},	% day
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='word_season'}	% word_season
    }.
field_map_to_msg('Proto50122001', FieldMap) ->
    #'Proto50122001'{
        'season' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50122002', FieldMap) ->
    #'Proto50122002'{
        'season' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'day' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'word_season' = gb_unserialize:get_value(maps:get(3,FieldMap))
    }.
