%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10110').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10110.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto80110002') ->
    #'Proto80110002'{'recharge_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='recharge_id'}	% recharge_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80110003') ->
    #'Proto80110003'{'recharge_info'=F1,'have_first'=F2,'get_first'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoRecharge',is_array=1,value=F1,field_name='recharge_info'},	% recharge_info
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='have_first'},	% have_first
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='get_first'}	% get_first
    ].
fetch_field_map('Proto80110002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='recharge_id'}	% recharge_id
    };
fetch_field_map('Proto80110003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoRecharge',is_array=1,field_name='recharge_info'},	% recharge_info
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='have_first'},	% have_first
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='get_first'}	% get_first
    }.
field_map_to_msg('Proto80110002', FieldMap) ->
    #'Proto80110002'{
        'recharge_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80110003', FieldMap) ->
    #'Proto80110003'{
        'recharge_info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'have_first' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'get_first' = gb_unserialize:get_value(maps:get(3,FieldMap))
    }.
