%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10140').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10140.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10140003') ->
    #'Proto10140003'{'type'=F1,'hero_list'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F2,field_name='hero_list'}	% hero_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10140004') ->
    #'Proto10140004'{'player_id'=F1,'type'=F2,'hero_list'=F3,'is_revenge'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='player_id'},	% player_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F3,field_name='hero_list'},	% hero_list
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='is_revenge'}	% is_revenge
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10140006') ->
    #'Proto10140006'{'type'=F1,'player_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F2,field_name='player_id'}	% player_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10140007') ->
    #'Proto10140007'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10140008') ->
    #'Proto10140008'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140001') ->
    #'Proto50140001'{'info'=F1,'rob_player_id'=F2,'astrology'=F3,'rob_times'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,value=F1,field_name='info'},	% info
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='rob_player_id'},	% rob_player_id
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='astrology'},	% astrology
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='rob_times'}	% rob_times
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140002') ->
    #'Proto50140002'{'hero_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F1,field_name='hero_list'}	% hero_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140004') ->
    #'Proto50140004'{'is_win'=F1,'star'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='is_win'},	% is_win
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='star'}	% star
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140005') ->
    #'Proto50140005'{'rob_info'=F1,'be_rob_info'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProroBattlefieldReport',is_array=1,value=F1,field_name='rob_info'},	% rob_info
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProroBattlefieldReport',is_array=1,value=F2,field_name='be_rob_info'}	% be_rob_info
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140006') ->
    #'Proto50140006'{'info'=F1,'player_info'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,value=F1,field_name='info'},	% info
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,value=F2,field_name='player_info'}	% player_info
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50140007') ->
    #'Proto50140007'{'id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='id'}	% id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80140009') ->
    #'Proto80140009'{'info'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,value=F1,field_name='info'}	% info
    ].
fetch_field_map('Proto10140003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'}	% hero_list
    };
fetch_field_map('Proto10140004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'},	% player_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'},	% hero_list
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_revenge'}	% is_revenge
    };
fetch_field_map('Proto10140006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='player_id'}	% player_id
    };
fetch_field_map('Proto10140007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10140008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto50140001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,field_name='info'},	% info
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='rob_player_id'},	% rob_player_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='astrology'},	% astrology
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='rob_times'}	% rob_times
    };
fetch_field_map('Proto50140002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='hero_list'}	% hero_list
    };
fetch_field_map('Proto50140004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_win'},	% is_win
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='star'}	% star
    };
fetch_field_map('Proto50140005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProroBattlefieldReport',is_array=1,field_name='rob_info'},	% rob_info
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProroBattlefieldReport',is_array=1,field_name='be_rob_info'}	% be_rob_info
    };
fetch_field_map('Proto50140006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,field_name='info'},	% info
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoShowRole',is_array=0,field_name='player_info'}	% player_info
    };
fetch_field_map('Proto50140007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='id'}	% id
    };
fetch_field_map('Proto80140009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoDragonPalace',is_array=1,field_name='info'}	% info
    }.
field_map_to_msg('Proto10140003', FieldMap) ->
    #'Proto10140003'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_list' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10140004', FieldMap) ->
    #'Proto10140004'{
        'player_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'hero_list' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'is_revenge' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto10140006', FieldMap) ->
    #'Proto10140006'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'player_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10140007', FieldMap) ->
    #'Proto10140007'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10140008', FieldMap) ->
    #'Proto10140008'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50140001', FieldMap) ->
    #'Proto50140001'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'rob_player_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'astrology' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'rob_times' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50140002', FieldMap) ->
    #'Proto50140002'{
        'hero_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50140004', FieldMap) ->
    #'Proto50140004'{
        'is_win' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'star' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50140005', FieldMap) ->
    #'Proto50140005'{
        'rob_info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'be_rob_info' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50140006', FieldMap) ->
    #'Proto50140006'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'player_info' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50140007', FieldMap) ->
    #'Proto50140007'{
        'id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80140009', FieldMap) ->
    #'Proto80140009'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
