%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10121').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10121.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10121003') ->
    #'Proto10121003'{'hero_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'}	% hero_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121004') ->
    #'Proto10121004'{'hero_id'=F1,'troops_march'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F2,field_name='troops_march'}	% troops_march
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121005') ->
    #'Proto10121005'{'hero_troops_march'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsHero',is_array=1,value=F1,field_name='hero_troops_march'}	% hero_troops_march
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121006') ->
    #'Proto10121006'{'hero_troops_march'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsHero',is_array=1,value=F1,field_name='hero_troops_march'}	% hero_troops_march
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121007') ->
    #'Proto10121007'{'hero_id'=F1,'prop_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='prop_id'}	% prop_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121008') ->
    #'Proto10121008'{'hero_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'}	% hero_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121009') ->
    #'Proto10121009'{'troops_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='troops_id'}	% troops_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121010') ->
    #'Proto10121010'{'hero_id'=F1,'type'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121011') ->
    #'Proto10121011'{'hero_id'=F1,'city_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10121012') ->
    #'Proto10121012'{'hero_id'=F1,'city_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121001') ->
    #'Proto50121001'{'troops_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=1,value=F1,field_name='troops_list'}	% troops_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121002') ->
    #'Proto50121002'{'hero_list'=F1,'bu_bing'=F2,'qi_bing'=F3,'gong_bing'=F4,'fa_shi'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHero',is_array=1,value=F1,field_name='hero_list'},	% hero_list
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='bu_bing'},	% bu_bing
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='qi_bing'},	% qi_bing
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='gong_bing'},	% gong_bing
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='fa_shi'}	% fa_shi
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121003') ->
    #'Proto50121003'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121004') ->
    #'Proto50121004'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121005') ->
    #'Proto50121005'{'consume_time'=F1,'consume_foodstuff'=F2,'consume_list'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='consume_time'},	% consume_time
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='consume_foodstuff'},	% consume_foodstuff
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoTroopsConsume',is_array=1,value=F3,field_name='consume_list'}	% consume_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121006') ->
    #'Proto50121006'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121007') ->
    #'Proto50121007'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121008') ->
    #'Proto50121008'{'flag'=F1,'troops_id'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'},	% flag
        #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F2,field_name='troops_id'}	% troops_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121009') ->
    #'Proto50121009'{'troops'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=0,value=F1,field_name='troops'}	% troops
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121010') ->
    #'Proto50121010'{'hero_id'=F1,'gold'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='gold'}	% gold
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121011') ->
    #'Proto50121011'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50121012') ->
    #'Proto50121012'{'flag'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='flag'}	% flag
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80121001') ->
    #'Proto80121001'{'troops_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=1,value=F1,field_name='troops_list'}	% troops_list
    ].
fetch_field_map('Proto10121003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'}	% hero_id
    };
fetch_field_map('Proto10121004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='troops_march'}	% troops_march
    };
fetch_field_map('Proto10121005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsHero',is_array=1,field_name='hero_troops_march'}	% hero_troops_march
    };
fetch_field_map('Proto10121006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsHero',is_array=1,field_name='hero_troops_march'}	% hero_troops_march
    };
fetch_field_map('Proto10121007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='prop_id'}	% prop_id
    };
fetch_field_map('Proto10121008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'}	% hero_id
    };
fetch_field_map('Proto10121009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='troops_id'}	% troops_id
    };
fetch_field_map('Proto10121010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10121011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10121012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50121001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=1,field_name='troops_list'}	% troops_list
    };
fetch_field_map('Proto50121002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHero',is_array=1,field_name='hero_list'},	% hero_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='bu_bing'},	% bu_bing
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='qi_bing'},	% qi_bing
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='gong_bing'},	% gong_bing
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='fa_shi'}	% fa_shi
    };
fetch_field_map('Proto50121003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto50121004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto50121005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='consume_time'},	% consume_time
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='consume_foodstuff'},	% consume_foodstuff
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoTroopsConsume',is_array=1,field_name='consume_list'}	% consume_list
    };
fetch_field_map('Proto50121006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto50121007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto50121008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'},	% flag
        2 => #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='troops_id'}	% troops_id
    };
fetch_field_map('Proto50121009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=0,field_name='troops'}	% troops
    };
fetch_field_map('Proto50121010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='gold'}	% gold
    };
fetch_field_map('Proto50121011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto50121012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='flag'}	% flag
    };
fetch_field_map('Proto80121001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroops',is_array=1,field_name='troops_list'}	% troops_list
    }.
field_map_to_msg('Proto10121003', FieldMap) ->
    #'Proto10121003'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10121004', FieldMap) ->
    #'Proto10121004'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'troops_march' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10121005', FieldMap) ->
    #'Proto10121005'{
        'hero_troops_march' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10121006', FieldMap) ->
    #'Proto10121006'{
        'hero_troops_march' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10121007', FieldMap) ->
    #'Proto10121007'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'prop_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10121008', FieldMap) ->
    #'Proto10121008'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10121009', FieldMap) ->
    #'Proto10121009'{
        'troops_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10121010', FieldMap) ->
    #'Proto10121010'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10121011', FieldMap) ->
    #'Proto10121011'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'city_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10121012', FieldMap) ->
    #'Proto10121012'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'city_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50121001', FieldMap) ->
    #'Proto50121001'{
        'troops_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121002', FieldMap) ->
    #'Proto50121002'{
        'hero_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'bu_bing' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'qi_bing' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'gong_bing' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'fa_shi' = gb_unserialize:get_value(maps:get(5,FieldMap))
    };
field_map_to_msg('Proto50121003', FieldMap) ->
    #'Proto50121003'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121004', FieldMap) ->
    #'Proto50121004'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121005', FieldMap) ->
    #'Proto50121005'{
        'consume_time' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'consume_foodstuff' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'consume_list' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50121006', FieldMap) ->
    #'Proto50121006'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121007', FieldMap) ->
    #'Proto50121007'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121008', FieldMap) ->
    #'Proto50121008'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'troops_id' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50121009', FieldMap) ->
    #'Proto50121009'{
        'troops' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121010', FieldMap) ->
    #'Proto50121010'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'gold' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50121011', FieldMap) ->
    #'Proto50121011'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50121012', FieldMap) ->
    #'Proto50121012'{
        'flag' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80121001', FieldMap) ->
    #'Proto80121001'{
        'troops_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
