%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10112').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10112.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto50112001') ->
    #'Proto50112001'{'vip_level'=F1,'recharge_money'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='vip_level'},	% vip_level
        #proto_field{field_tag=2,wire_type=1,data_type=5,data_type_name='undefined',is_array=0,value=F2,field_name='recharge_money'}	% recharge_money
    ].
fetch_field_map('Proto50112001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='vip_level'},	% vip_level
        2 => #proto_field{field_tag=2,wire_type=1,data_type=5,data_type_name='undefined',is_array=0,field_name='recharge_money'}	% recharge_money
    }.
field_map_to_msg('Proto50112001', FieldMap) ->
    #'Proto50112001'{
        'vip_level' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'recharge_money' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
