%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10157').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10157.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10157001') ->
    #'Proto10157001'{'trigger_type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='trigger_type'}	% trigger_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10157002') ->
    #'Proto10157002'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10157003') ->
    #'Proto10157003'{'award_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='award_id'}	% award_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50157001') ->
    #'Proto50157001'{'trigger_status'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='trigger_status'}	% trigger_status
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50157002') ->
    #'Proto50157002'{'welfare_event_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoWelfareExchange',is_array=1,value=F1,field_name='welfare_event_list'}	% welfare_event_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50157003') ->
    #'Proto50157003'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80157004') ->
    #'Proto80157004'{'type'=F1,'residual_time'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='residual_time'}	% residual_time
    ].
fetch_field_map('Proto10157001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='trigger_type'}	% trigger_type
    };
fetch_field_map('Proto10157002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10157003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='award_id'}	% award_id
    };
fetch_field_map('Proto50157001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='trigger_status'}	% trigger_status
    };
fetch_field_map('Proto50157002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoWelfareExchange',is_array=1,field_name='welfare_event_list'}	% welfare_event_list
    };
fetch_field_map('Proto50157003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto80157004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='residual_time'}	% residual_time
    }.
field_map_to_msg('Proto10157001', FieldMap) ->
    #'Proto10157001'{
        'trigger_type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10157002', FieldMap) ->
    #'Proto10157002'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10157003', FieldMap) ->
    #'Proto10157003'{
        'award_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50157001', FieldMap) ->
    #'Proto50157001'{
        'trigger_status' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50157002', FieldMap) ->
    #'Proto50157002'{
        'welfare_event_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50157003', FieldMap) ->
    #'Proto50157003'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80157004', FieldMap) ->
    #'Proto80157004'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'residual_time' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
