%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10135').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10135.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10135001') ->
    #'Proto10135001'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10135002') ->
    #'Proto10135002'{'science_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='science_id'}	% science_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10135003') ->
    #'Proto10135003'{'stage'=F1,'index'=F2,'science_id'=F3,'type'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='stage'},	% stage
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='index'},	% index
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='science_id'},	% science_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10135004') ->
    #'Proto10135004'{'science_id'=F1,'type'=F2,'item_id'=F3,'amount'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='science_id'},	% science_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='item_id'},	% item_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='amount'}	% amount
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10135005') ->
    #'Proto10135005'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10135006') ->
    #'Proto10135006'{'science_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='science_id'}	% science_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135001') ->
    #'Proto50135001'{'science_list'=F1,'is_received'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=1,value=F1,field_name='science_list'},	% science_list
        #proto_field{field_tag=2,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F2,field_name='is_received'}	% is_received
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135002') ->
    #'Proto50135002'{'science'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=0,value=F1,field_name='science'}	% science
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135003') ->
    #'Proto50135003'{'stage'=F1,'index'=F2,'science_id'=F3,'type'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='stage'},	% stage
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='index'},	% index
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='science_id'},	% science_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135004') ->
    #'Proto50135004'{'science_id'=F1,'type'=F2,'item_id'=F3,'amount'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='science_id'},	% science_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='item_id'},	% item_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='amount'}	% amount
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135005') ->
    #'Proto50135005'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50135006') ->
    #'Proto50135006'{'science_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='science_id'}	% science_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80135001') ->
    #'Proto80135001'{'science_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=1,value=F1,field_name='science_list'}	% science_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80135002') ->
    #'Proto80135002'{'is_received'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,value=F1,field_name='is_received'}	% is_received
    ].
fetch_field_map('Proto10135001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10135002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'}	% science_id
    };
fetch_field_map('Proto10135003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='stage'},	% stage
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'},	% science_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10135004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'},	% science_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='item_id'},	% item_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='amount'}	% amount
    };
fetch_field_map('Proto10135005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10135006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'}	% science_id
    };
fetch_field_map('Proto50135001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=1,field_name='science_list'},	% science_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_received'}	% is_received
    };
fetch_field_map('Proto50135002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=0,field_name='science'}	% science
    };
fetch_field_map('Proto50135003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='stage'},	% stage
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'},	% science_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto50135004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'},	% science_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='item_id'},	% item_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='amount'}	% amount
    };
fetch_field_map('Proto50135005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto50135006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='science_id'}	% science_id
    };
fetch_field_map('Proto80135001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoScience',is_array=1,field_name='science_list'}	% science_list
    };
fetch_field_map('Proto80135002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=8,data_type_name='undefined',is_array=0,field_name='is_received'}	% is_received
    }.
field_map_to_msg('Proto10135001', FieldMap) ->
    #'Proto10135001'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10135002', FieldMap) ->
    #'Proto10135002'{
        'science_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10135003', FieldMap) ->
    #'Proto10135003'{
        'stage' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'science_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto10135004', FieldMap) ->
    #'Proto10135004'{
        'science_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'item_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'amount' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto10135005', FieldMap) ->
    #'Proto10135005'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10135006', FieldMap) ->
    #'Proto10135006'{
        'science_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50135001', FieldMap) ->
    #'Proto50135001'{
        'science_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'is_received' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50135002', FieldMap) ->
    #'Proto50135002'{
        'science' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50135003', FieldMap) ->
    #'Proto50135003'{
        'stage' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'science_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50135004', FieldMap) ->
    #'Proto50135004'{
        'science_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'item_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'amount' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50135005', FieldMap) ->
    #'Proto50135005'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50135006', FieldMap) ->
    #'Proto50135006'{
        'science_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80135001', FieldMap) ->
    #'Proto80135001'{
        'science_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80135002', FieldMap) ->
    #'Proto80135002'{
        'is_received' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
