%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10103').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10103.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10103001') ->
    #'Proto10103001'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10103003') ->
    #'Proto10103003'{'pack_type'=F1,'unique_id'=F2,'amount'=F3,'use_argv'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='pack_type'},	% pack_type
        #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F2,field_name='unique_id'},	% unique_id
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='amount'},	% amount
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='use_argv'}	% use_argv
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103002') ->
    #'Proto80103002'{'type'=F1,'max_size'=F2,'item_list'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='max_size'},	% max_size
        #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F3,field_name='item_list'}	% item_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103004') ->
    #'Proto80103004'{'money_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMoney',is_array=1,value=F1,field_name='money_list'}	% money_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103005') ->
    #'Proto80103005'{'item_list'=F1,'tips_type'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F1,field_name='item_list'},	% item_list
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='tips_type'}	% tips_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103006') ->
    #'Proto80103006'{'type'=F1,'item_list'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F2,field_name='item_list'}	% item_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103007') ->
    #'Proto80103007'{'type'=F1,'item_list'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F2,field_name='item_list'}	% item_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80103008') ->
    #'Proto80103008'{'type'=F1,'item_list'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,value=F2,field_name='item_list'}	% item_list
    ].
fetch_field_map('Proto10103001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10103003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='pack_type'},	% pack_type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='unique_id'},	% unique_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='amount'},	% amount
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='use_argv'}	% use_argv
    };
fetch_field_map('Proto80103002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='max_size'},	% max_size
        3 => #proto_field{field_tag=3,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'}	% item_list
    };
fetch_field_map('Proto80103004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMoney',is_array=1,field_name='money_list'}	% money_list
    };
fetch_field_map('Proto80103005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'},	% item_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='tips_type'}	% tips_type
    };
fetch_field_map('Proto80103006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'}	% item_list
    };
fetch_field_map('Proto80103007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'}	% item_list
    };
fetch_field_map('Proto80103008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoItem',is_array=1,field_name='item_list'}	% item_list
    }.
field_map_to_msg('Proto10103001', FieldMap) ->
    #'Proto10103001'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10103003', FieldMap) ->
    #'Proto10103003'{
        'pack_type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'unique_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'amount' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'use_argv' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto80103002', FieldMap) ->
    #'Proto80103002'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'max_size' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'item_list' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto80103004', FieldMap) ->
    #'Proto80103004'{
        'money_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80103005', FieldMap) ->
    #'Proto80103005'{
        'item_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'tips_type' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80103006', FieldMap) ->
    #'Proto80103006'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'item_list' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80103007', FieldMap) ->
    #'Proto80103007'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'item_list' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80103008', FieldMap) ->
    #'Proto80103008'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'item_list' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
