%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10141').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10141.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10141001') ->
    #'Proto10141001'{'city_id'=F1,'hero_id'=F2,'type'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'},	% city_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50141002') ->
    #'Proto50141002'{'city_visiting'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCityVisiting',is_array=1,value=F1,field_name='city_visiting'}	% city_visiting
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80141002') ->
    #'Proto80141002'{'city_visiting'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCityVisiting',is_array=0,value=F1,field_name='city_visiting'}	% city_visiting
    ].
fetch_field_map('Proto10141001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'},	% city_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto50141002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCityVisiting',is_array=1,field_name='city_visiting'}	% city_visiting
    };
fetch_field_map('Proto80141002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoCityVisiting',is_array=0,field_name='city_visiting'}	% city_visiting
    }.
field_map_to_msg('Proto10141001', FieldMap) ->
    #'Proto10141001'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50141002', FieldMap) ->
    #'Proto50141002'{
        'city_visiting' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80141002', FieldMap) ->
    #'Proto80141002'{
        'city_visiting' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
