%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10114').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10114.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10114008') ->
    #'Proto10114008'{'clearing_id'=F1,'hero_id'=F2,'hero_id_list'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='clearing_id'},	% clearing_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F3,field_name='hero_id_list'}	% hero_id_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10114011') ->
    #'Proto10114011'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10114012') ->
    #'Proto10114012'{'clearing_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,value=F1,field_name='clearing_id'}	% clearing_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10114100') ->
    #'Proto10114100'{'city_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F1,field_name='city_id'}	% city_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114001') ->
    #'Proto50114001'{'back_map_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMap',is_array=1,value=F1,field_name='back_map_list'}	% back_map_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114002') ->
    #'Proto50114002'{'map_clearing_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapClearing',is_array=1,value=F1,field_name='map_clearing_list'}	% map_clearing_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114009') ->
    #'Proto50114009'{'map_industry'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapIndustry',is_array=1,value=F1,field_name='map_industry'}	% map_industry
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114010') ->
    #'Proto50114010'{'gensis_church'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoGenesisChurch',is_array=1,value=F1,field_name='gensis_church'}	% gensis_church
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114011') ->
    #'Proto50114011'{'gold'=F1,'silver'=F2,'food'=F3,'troops_list'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='gold'},	% gold
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='silver'},	% silver
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='food'},	% food
        #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoTroopsDetail',is_array=1,value=F4,field_name='troops_list'}	% troops_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50114012') ->
    #'Proto50114012'{'type'=F1,'p1'=F2,'p2'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='p1'},	% p1
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='p2'}	% p2
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114001') ->
    #'Proto80114001'{'back_map_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMap',is_array=1,value=F1,field_name='back_map_list'}	% back_map_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114002') ->
    #'Proto80114002'{'map_clearing'=F1,'state'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapClearing',is_array=0,value=F1,field_name='map_clearing'},	% map_clearing
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='state'}	% state
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114003') ->
    #'Proto80114003'{'troops_notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsNotice',is_array=1,value=F1,field_name='troops_notice'}	% troops_notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114004') ->
    #'Proto80114004'{'troops_id'=F1,'remaining_time'=F2,'rate'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='troops_id'},	% troops_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='remaining_time'},	% remaining_time
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='rate'}	% rate
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114005') ->
    #'Proto80114005'{'troops_id'=F1,'remaining_time'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='troops_id'},	% troops_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='remaining_time'}	% remaining_time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114006') ->
    #'Proto80114006'{'troops_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F1,field_name='troops_id'}	% troops_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114007') ->
    #'Proto80114007'{'troops_notice'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsNotice',is_array=1,value=F1,field_name='troops_notice'}	% troops_notice
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114009') ->
    #'Proto80114009'{'state'=F1,'map_industry'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='state'},	% state
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoMapIndustry',is_array=1,value=F2,field_name='map_industry'}	% map_industry
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80114010') ->
    #'Proto80114010'{'type'=F1,'genesis_church'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoGenesisChurch',is_array=1,value=F2,field_name='genesis_church'}	% genesis_church
    ].
fetch_field_map('Proto10114008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='clearing_id'},	% clearing_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_id_list'}	% hero_id_list
    };
fetch_field_map('Proto10114011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto10114012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=7,data_type_name='undefined',is_array=0,field_name='clearing_id'}	% clearing_id
    };
fetch_field_map('Proto10114100') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='city_id'}	% city_id
    };
fetch_field_map('Proto50114001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMap',is_array=1,field_name='back_map_list'}	% back_map_list
    };
fetch_field_map('Proto50114002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapClearing',is_array=1,field_name='map_clearing_list'}	% map_clearing_list
    };
fetch_field_map('Proto50114009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapIndustry',is_array=1,field_name='map_industry'}	% map_industry
    };
fetch_field_map('Proto50114010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoGenesisChurch',is_array=1,field_name='gensis_church'}	% gensis_church
    };
fetch_field_map('Proto50114011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='gold'},	% gold
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='silver'},	% silver
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='food'},	% food
        4 => #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoTroopsDetail',is_array=1,field_name='troops_list'}	% troops_list
    };
fetch_field_map('Proto50114012') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='p1'},	% p1
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='p2'}	% p2
    };
fetch_field_map('Proto80114001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMap',is_array=1,field_name='back_map_list'}	% back_map_list
    };
fetch_field_map('Proto80114002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoMapClearing',is_array=0,field_name='map_clearing'},	% map_clearing
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='state'}	% state
    };
fetch_field_map('Proto80114003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsNotice',is_array=1,field_name='troops_notice'}	% troops_notice
    };
fetch_field_map('Proto80114004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='troops_id'},	% troops_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='remaining_time'},	% remaining_time
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='rate'}	% rate
    };
fetch_field_map('Proto80114005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='troops_id'},	% troops_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='remaining_time'}	% remaining_time
    };
fetch_field_map('Proto80114006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='troops_id'}	% troops_id
    };
fetch_field_map('Proto80114007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoTroopsNotice',is_array=1,field_name='troops_notice'}	% troops_notice
    };
fetch_field_map('Proto80114009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='state'},	% state
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoMapIndustry',is_array=1,field_name='map_industry'}	% map_industry
    };
fetch_field_map('Proto80114010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoGenesisChurch',is_array=1,field_name='genesis_church'}	% genesis_church
    }.
field_map_to_msg('Proto10114008', FieldMap) ->
    #'Proto10114008'{
        'clearing_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'hero_id_list' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto10114011', FieldMap) ->
    #'Proto10114011'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10114012', FieldMap) ->
    #'Proto10114012'{
        'clearing_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10114100', FieldMap) ->
    #'Proto10114100'{
        'city_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50114001', FieldMap) ->
    #'Proto50114001'{
        'back_map_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50114002', FieldMap) ->
    #'Proto50114002'{
        'map_clearing_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50114009', FieldMap) ->
    #'Proto50114009'{
        'map_industry' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50114010', FieldMap) ->
    #'Proto50114010'{
        'gensis_church' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50114011', FieldMap) ->
    #'Proto50114011'{
        'gold' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'silver' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'food' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'troops_list' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50114012', FieldMap) ->
    #'Proto50114012'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'p1' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'p2' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto80114001', FieldMap) ->
    #'Proto80114001'{
        'back_map_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80114002', FieldMap) ->
    #'Proto80114002'{
        'map_clearing' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'state' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80114003', FieldMap) ->
    #'Proto80114003'{
        'troops_notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80114004', FieldMap) ->
    #'Proto80114004'{
        'troops_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'remaining_time' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'rate' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto80114005', FieldMap) ->
    #'Proto80114005'{
        'troops_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'remaining_time' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80114006', FieldMap) ->
    #'Proto80114006'{
        'troops_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80114007', FieldMap) ->
    #'Proto80114007'{
        'troops_notice' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80114009', FieldMap) ->
    #'Proto80114009'{
        'state' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'map_industry' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto80114010', FieldMap) ->
    #'Proto80114010'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'genesis_church' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
