%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10124').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10124.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10124002') ->
    #'Proto10124002'{'type'=F1,'item_type'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'},	% type
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='item_type'}	% item_type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50124001') ->
    #'Proto50124001'{'residue_degree'=F1,'sum_degree'=F2,'time_to_special'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='residue_degree'},	% residue_degree
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='sum_degree'},	% sum_degree
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='time_to_special'}	% time_to_special
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50124002') ->
    #'Proto50124002'{'item_list'=F1,'type'=F2,'surplus_time'=F3,'sum_degree'=F4,'time_to_special'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoItemObj',is_array=1,value=F1,field_name='item_list'},	% item_list
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='surplus_time'},	% surplus_time
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='sum_degree'},	% sum_degree
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='time_to_special'}	% time_to_special
    ].
fetch_field_map('Proto10124002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='item_type'}	% item_type
    };
fetch_field_map('Proto50124001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='residue_degree'},	% residue_degree
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='sum_degree'},	% sum_degree
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='time_to_special'}	% time_to_special
    };
fetch_field_map('Proto50124002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoItemObj',is_array=1,field_name='item_list'},	% item_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='surplus_time'},	% surplus_time
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='sum_degree'},	% sum_degree
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='time_to_special'}	% time_to_special
    }.
field_map_to_msg('Proto10124002', FieldMap) ->
    #'Proto10124002'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'item_type' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50124001', FieldMap) ->
    #'Proto50124001'{
        'residue_degree' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'sum_degree' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'time_to_special' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50124002', FieldMap) ->
    #'Proto50124002'{
        'item_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'surplus_time' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'sum_degree' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'time_to_special' = gb_unserialize:get_value(maps:get(5,FieldMap))
    }.
