%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10144').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10144.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10144001') ->
    #'Proto10144001'{'shop_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='shop_id'}	% shop_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10144002') ->
    #'Proto10144002'{'shop_id'=F1,'index'=F2,'grid_id'=F3,'goods_id'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='shop_id'},	% shop_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='index'},	% index
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='grid_id'},	% grid_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='goods_id'}	% goods_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10144003') ->
    #'Proto10144003'{'shop_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='shop_id'}	% shop_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10144004') ->
    #'Proto10144004'{'prop_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='prop_id'}	% prop_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50144001') ->
    #'Proto50144001'{'shop'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShop',is_array=0,value=F1,field_name='shop'}	% shop
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50144002') ->
    #'Proto50144002'{'shop_id'=F1,'index'=F2,'grid_id'=F3,'goods_id'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='shop_id'},	% shop_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='index'},	% index
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='grid_id'},	% grid_id
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='goods_id'}	% goods_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50144003') ->
    #'Proto50144003'{'shop_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='shop_id'}	% shop_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50144004') ->
    #'Proto50144004'{'num_limit'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='num_limit'}	% num_limit
    ].
fetch_field_map('Proto10144001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='shop_id'}	% shop_id
    };
fetch_field_map('Proto10144002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='shop_id'},	% shop_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='grid_id'},	% grid_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='goods_id'}	% goods_id
    };
fetch_field_map('Proto10144003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='shop_id'}	% shop_id
    };
fetch_field_map('Proto10144004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='prop_id'}	% prop_id
    };
fetch_field_map('Proto50144001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoShop',is_array=0,field_name='shop'}	% shop
    };
fetch_field_map('Proto50144002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='shop_id'},	% shop_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='index'},	% index
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='grid_id'},	% grid_id
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='goods_id'}	% goods_id
    };
fetch_field_map('Proto50144003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='shop_id'}	% shop_id
    };
fetch_field_map('Proto50144004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='num_limit'}	% num_limit
    }.
field_map_to_msg('Proto10144001', FieldMap) ->
    #'Proto10144001'{
        'shop_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10144002', FieldMap) ->
    #'Proto10144002'{
        'shop_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'grid_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'goods_id' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto10144003', FieldMap) ->
    #'Proto10144003'{
        'shop_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10144004', FieldMap) ->
    #'Proto10144004'{
        'prop_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50144001', FieldMap) ->
    #'Proto50144001'{
        'shop' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50144002', FieldMap) ->
    #'Proto50144002'{
        'shop_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'index' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'grid_id' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'goods_id' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto50144003', FieldMap) ->
    #'Proto50144003'{
        'shop_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50144004', FieldMap) ->
    #'Proto50144004'{
        'num_limit' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
