%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10149').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10149.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10149001') ->
    #'Proto10149001'{'stage'=F1,'group'=F2,'type'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='stage'},	% stage
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='group'},	% group
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10149003') ->
    #'Proto10149003'{'hero_list'=F1,'is_apply'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F1,field_name='hero_list'},	% hero_list
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='is_apply'}	% is_apply
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10149005') ->
    #'Proto10149005'{'stage'=F1,'group'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='stage'},	% stage
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='group'}	% group
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10149008') ->
    #'Proto10149008'{'rank'=F1,'money'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='rank'},	% rank
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='money'}	% money
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10149010') ->
    #'Proto10149010'{'type'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='type'}	% type
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149001') ->
    #'Proto50149001'{'stage'=F1,'times'=F2,'group'=F3,'info'=F4,'tick'=F5,'activity_time'=F6,'is_apply'=F7,'is_fight'=F8}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='stage'},	% stage
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='times'},	% times
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='group'},	% group
        #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,value=F4,field_name='info'},	% info
        #proto_field{field_tag=5,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F5,field_name='tick'},	% tick
        #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F6,field_name='activity_time'},	% activity_time
        #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F7,field_name='is_apply'},	% is_apply
        #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F8,field_name='is_fight'}	% is_fight
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149002') ->
    #'Proto50149002'{'info'=F1,'is_worship'=F2,'activity_time'=F3,'is_apply'=F4,'apply_num'=F5}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,value=F1,field_name='info'},	% info
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='is_worship'},	% is_worship
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='activity_time'},	% activity_time
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='is_apply'},	% is_apply
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='apply_num'}	% apply_num
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149005') ->
    #'Proto50149005'{'report_info'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTopReport',is_array=1,value=F1,field_name='report_info'}	% report_info
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149006') ->
    #'Proto50149006'{'player_info'=F1,'reoprt'=F2,'tick'=F3,'times'=F4,'activity_time'=F5,'is_fight'=F6,'bet'=F7}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,value=F1,field_name='player_info'},	% player_info
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoHonourTopReport',is_array=1,value=F2,field_name='reoprt'},	% reoprt
        #proto_field{field_tag=3,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,value=F3,field_name='tick'},	% tick
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='times'},	% times
        #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F5,field_name='activity_time'},	% activity_time
        #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F6,field_name='is_fight'},	% is_fight
        #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F7,field_name='bet'}	% bet
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149007') ->
    #'Proto50149007'{'info'=F1,'bet'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,value=F1,field_name='info'},	% info
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='bet'}	% bet
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149008') ->
    #'Proto50149008'{'is_success'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='is_success'}	% is_success
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50149009') ->
    #'Proto50149009'{'hero_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F1,field_name='hero_list'}	% hero_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80149011') ->
    #'Proto80149011'{'is_fight'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='is_fight'}	% is_fight
    ].
fetch_field_map('Proto10149001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='stage'},	% stage
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='group'},	% group
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto10149003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'},	% hero_list
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_apply'}	% is_apply
    };
fetch_field_map('Proto10149005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='stage'},	% stage
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='group'}	% group
    };
fetch_field_map('Proto10149008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='rank'},	% rank
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='money'}	% money
    };
fetch_field_map('Proto10149010') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'}	% type
    };
fetch_field_map('Proto50149001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='stage'},	% stage
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='times'},	% times
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='group'},	% group
        4 => #proto_field{field_tag=4,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,field_name='info'},	% info
        5 => #proto_field{field_tag=5,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='tick'},	% tick
        6 => #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='activity_time'},	% activity_time
        7 => #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_apply'},	% is_apply
        8 => #proto_field{field_tag=8,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_fight'}	% is_fight
    };
fetch_field_map('Proto50149002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,field_name='info'},	% info
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_worship'},	% is_worship
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='activity_time'},	% activity_time
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_apply'},	% is_apply
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='apply_num'}	% apply_num
    };
fetch_field_map('Proto50149005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTopReport',is_array=1,field_name='report_info'}	% report_info
    };
fetch_field_map('Proto50149006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,field_name='player_info'},	% player_info
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoHonourTopReport',is_array=1,field_name='reoprt'},	% reoprt
        3 => #proto_field{field_tag=3,wire_type=0,data_type=2,data_type_name='undefined',is_array=0,field_name='tick'},	% tick
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='times'},	% times
        5 => #proto_field{field_tag=5,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='activity_time'},	% activity_time
        6 => #proto_field{field_tag=6,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_fight'},	% is_fight
        7 => #proto_field{field_tag=7,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='bet'}	% bet
    };
fetch_field_map('Proto50149007') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHonourTop',is_array=1,field_name='info'},	% info
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='bet'}	% bet
    };
fetch_field_map('Proto50149008') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_success'}	% is_success
    };
fetch_field_map('Proto50149009') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='hero_list'}	% hero_list
    };
fetch_field_map('Proto80149011') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='is_fight'}	% is_fight
    }.
field_map_to_msg('Proto10149001', FieldMap) ->
    #'Proto10149001'{
        'stage' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'group' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto10149003', FieldMap) ->
    #'Proto10149003'{
        'hero_list' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'is_apply' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10149005', FieldMap) ->
    #'Proto10149005'{
        'stage' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'group' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10149008', FieldMap) ->
    #'Proto10149008'{
        'rank' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'money' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto10149010', FieldMap) ->
    #'Proto10149010'{
        'type' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50149001', FieldMap) ->
    #'Proto50149001'{
        'stage' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'times' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'group' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'info' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'tick' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'activity_time' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'is_apply' = gb_unserialize:get_value(maps:get(7,FieldMap)),
        'is_fight' = gb_unserialize:get_value(maps:get(8,FieldMap))
    };
field_map_to_msg('Proto50149002', FieldMap) ->
    #'Proto50149002'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'is_worship' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'activity_time' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'is_apply' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'apply_num' = gb_unserialize:get_value(maps:get(5,FieldMap))
    };
field_map_to_msg('Proto50149005', FieldMap) ->
    #'Proto50149005'{
        'report_info' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50149006', FieldMap) ->
    #'Proto50149006'{
        'player_info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'reoprt' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'tick' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'times' = gb_unserialize:get_value(maps:get(4,FieldMap)),
        'activity_time' = gb_unserialize:get_value(maps:get(5,FieldMap)),
        'is_fight' = gb_unserialize:get_value(maps:get(6,FieldMap)),
        'bet' = gb_unserialize:get_value(maps:get(7,FieldMap))
    };
field_map_to_msg('Proto50149007', FieldMap) ->
    #'Proto50149007'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'bet' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50149008', FieldMap) ->
    #'Proto50149008'{
        'is_success' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50149009', FieldMap) ->
    #'Proto50149009'{
        'hero_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80149011', FieldMap) ->
    #'Proto80149011'{
        'is_fight' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
