%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10138').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10138.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10138001') ->
    #'Proto10138001'{'other'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='other'}	% other
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10138003') ->
    #'Proto10138003'{'hero_id'=F1,'type'=F2,'num'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='num'}	% num
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10138004') ->
    #'Proto10138004'{'hero_id'=F1,'state'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='state'}	% state
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50138001') ->
    #'Proto50138001'{'hero_busy_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHeroBusy',is_array=1,value=F1,field_name='hero_busy_list'}	% hero_busy_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50138003') ->
    #'Proto50138003'{'hero_id'=F1,'total_time'=F2,'remaining_time'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='total_time'},	% total_time
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='remaining_time'}	% remaining_time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80138001') ->
    #'Proto80138001'{'state'=F1,'hero_busy_list'=F2}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='state'},	% state
        #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoHeroBusy',is_array=1,value=F2,field_name='hero_busy_list'}	% hero_busy_list
    ].
fetch_field_map('Proto10138001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='other'}	% other
    };
fetch_field_map('Proto10138003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='num'}	% num
    };
fetch_field_map('Proto10138004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='state'}	% state
    };
fetch_field_map('Proto50138001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoHeroBusy',is_array=1,field_name='hero_busy_list'}	% hero_busy_list
    };
fetch_field_map('Proto50138003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='total_time'},	% total_time
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='remaining_time'}	% remaining_time
    };
fetch_field_map('Proto80138001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='state'},	% state
        2 => #proto_field{field_tag=2,wire_type=2,data_type=16,data_type_name='ProtoHeroBusy',is_array=1,field_name='hero_busy_list'}	% hero_busy_list
    }.
field_map_to_msg('Proto10138001', FieldMap) ->
    #'Proto10138001'{
        'other' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10138003', FieldMap) ->
    #'Proto10138003'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'num' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto10138004', FieldMap) ->
    #'Proto10138004'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'state' = gb_unserialize:get_value(maps:get(2,FieldMap))
    };
field_map_to_msg('Proto50138001', FieldMap) ->
    #'Proto50138001'{
        'hero_busy_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50138003', FieldMap) ->
    #'Proto50138003'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'total_time' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'remaining_time' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto80138001', FieldMap) ->
    #'Proto80138001'{
        'state' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'hero_busy_list' = gb_unserialize:get_value(maps:get(2,FieldMap))
    }.
