%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10151').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10151.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10151002') ->
    #'Proto10151002'{'time'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='time'}	% time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10151003') ->
    #'Proto10151003'{'item_list'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,value=F1,field_name='item_list'}	% item_list
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10151005') ->
    #'Proto10151005'{'hero_id'=F1,'type'=F2,'inlay_type'=F3,'item_id'=F4}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='type'},	% type
        #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F3,field_name='inlay_type'},	% inlay_type
        #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F4,field_name='item_id'}	% item_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto10151006') ->
    #'Proto10151006'{'hero_id'=F1,'item_id'=F2,'ues_item'=F3}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='hero_id'},	% hero_id
        #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F2,field_name='item_id'},	% item_id
        #proto_field{field_tag=3,wire_type=0,data_type=3,data_type_name='undefined',is_array=0,value=F3,field_name='ues_item'}	% ues_item
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50151001') ->
    #'Proto50151001'{'buy_time'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='buy_time'}	% buy_time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50151002') ->
    #'Proto50151002'{'buy_time'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='buy_time'}	% buy_time
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50151004') ->
    #'Proto50151004'{'level_info'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,value=F1,field_name='level_info'}	% level_info
    ].
fetch_field_map('Proto10151002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='time'}	% time
    };
fetch_field_map('Proto10151003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=1,field_name='item_list'}	% item_list
    };
fetch_field_map('Proto10151005') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='type'},	% type
        3 => #proto_field{field_tag=3,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='inlay_type'},	% inlay_type
        4 => #proto_field{field_tag=4,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='item_id'}	% item_id
    };
fetch_field_map('Proto10151006') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='hero_id'},	% hero_id
        2 => #proto_field{field_tag=2,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='item_id'},	% item_id
        3 => #proto_field{field_tag=3,wire_type=0,data_type=3,data_type_name='undefined',is_array=0,field_name='ues_item'}	% ues_item
    };
fetch_field_map('Proto50151001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='buy_time'}	% buy_time
    };
fetch_field_map('Proto50151002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='buy_time'}	% buy_time
    };
fetch_field_map('Proto50151004') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoKeyValue',is_array=1,field_name='level_info'}	% level_info
    }.
field_map_to_msg('Proto10151002', FieldMap) ->
    #'Proto10151002'{
        'time' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10151003', FieldMap) ->
    #'Proto10151003'{
        'item_list' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto10151005', FieldMap) ->
    #'Proto10151005'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'type' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'inlay_type' = gb_unserialize:get_value(maps:get(3,FieldMap)),
        'item_id' = gb_unserialize:get_value(maps:get(4,FieldMap))
    };
field_map_to_msg('Proto10151006', FieldMap) ->
    #'Proto10151006'{
        'hero_id' = gb_unserialize:get_value(maps:get(1,FieldMap)),
        'item_id' = gb_unserialize:get_value(maps:get(2,FieldMap)),
        'ues_item' = gb_unserialize:get_value(maps:get(3,FieldMap))
    };
field_map_to_msg('Proto50151001', FieldMap) ->
    #'Proto50151001'{
        'buy_time' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50151002', FieldMap) ->
    #'Proto50151002'{
        'buy_time' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50151004', FieldMap) ->
    #'Proto50151004'{
        'level_info' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
