%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-module('ProtoClient_10120').
-export([encode_msg/1,encode_msg/2]).
-export([decode_msg/2]).
-include("ProtoClient_10120.hrl").
-include("ProtoPublic.hrl").
-include("protobuffer.hrl").
encode_msg(Msg) ->
	encode_msg(Msg, element(1, Msg)).
encode_msg(Msg, MsgName)->
	SerialFieldList = convert_field_list(Msg),
	gb_serialize:serialize_field_list(SerialFieldList, MsgName).
decode_msg(DataBin, MsgNameAtom) ->
	FieldMap = fetch_field_map(MsgNameAtom),
	NewFieldMap = gb_unserialize:unserialize_field_list(DataBin, FieldMap),
	field_map_to_msg(MsgNameAtom, NewFieldMap).
convert_field_list(Msg) when is_record(Msg, 'Proto10120002') ->
    #'Proto10120002'{'head_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='head_id'}	% head_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50120001') ->
    #'Proto50120001'{'info'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoPairLong',is_array=1,value=F1,field_name='info'}	% info
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto50120002') ->
    #'Proto50120002'{'head_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='head_id'}	% head_id
    ];
convert_field_list(Msg) when is_record(Msg, 'Proto80120003') ->
    #'Proto80120003'{'head_id'=F1}=Msg,
    [
        #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,value=F1,field_name='head_id'}	% head_id
    ].
fetch_field_map('Proto10120002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='head_id'}	% head_id
    };
fetch_field_map('Proto50120001') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=2,data_type=16,data_type_name='ProtoPairLong',is_array=1,field_name='info'}	% info
    };
fetch_field_map('Proto50120002') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='head_id'}	% head_id
    };
fetch_field_map('Proto80120003') ->
    #{
        1 => #proto_field{field_tag=1,wire_type=0,data_type=1,data_type_name='undefined',is_array=0,field_name='head_id'}	% head_id
    }.
field_map_to_msg('Proto10120002', FieldMap) ->
    #'Proto10120002'{
        'head_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50120001', FieldMap) ->
    #'Proto50120001'{
        'info' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto50120002', FieldMap) ->
    #'Proto50120002'{
        'head_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    };
field_map_to_msg('Proto80120003', FieldMap) ->
    #'Proto80120003'{
        'head_id' = gb_unserialize:get_value(maps:get(1,FieldMap))
    }.
