%%--- coding:utf-8 ---
-module(tb_building_open).
-export([get/1,get_list/0]).
get(1010101)-> #{
    'name' => <<"14356"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 4500,
    'wood' => 6000,
    'iron' => 3500,
    'time' => 0,
    'building_a_id' => 0,
    'building_a_num' => 0,
    'building_a_lv' => 0,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1020101)-> #{
    'name' => <<"16556"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 3400,
    'wood' => 2000,
    'iron' => 2200,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 2,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120101)-> #{
    'name' => <<"16505"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 500,
    'wood' => 500,
    'iron' => 500,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120102)-> #{
    'name' => <<"16505"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 500,
    'wood' => 500,
    'iron' => 500,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 6,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120103)-> #{
    'name' => <<"16505"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 500,
    'wood' => 500,
    'iron' => 500,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 10,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120301)-> #{
    'name' => <<"16508"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 300,
    'wood' => 600,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120302)-> #{
    'name' => <<"16508"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 300,
    'wood' => 600,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 5,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120303)-> #{
    'name' => <<"16508"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 300,
    'wood' => 600,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 9,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120401)-> #{
    'name' => <<"16510"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 300,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120402)-> #{
    'name' => <<"16510"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 300,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 8,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120403)-> #{
    'name' => <<"16510"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 300,
    'iron' => 600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 10,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120201)-> #{
    'name' => <<"521"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 600,
    'iron' => 300,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120202)-> #{
    'name' => <<"521"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 600,
    'iron' => 300,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 8,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1120203)-> #{
    'name' => <<"521"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 600,
    'wood' => 600,
    'iron' => 300,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 10,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1090101)-> #{
    'name' => <<"16558"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 3000,
    'wood' => 1000,
    'iron' => 1400,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 5,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1060101)-> #{
    'name' => <<"16487"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 1000,
    'wood' => 1100,
    'iron' => 1700,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1060201)-> #{
    'name' => <<"16488"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 1000,
    'wood' => 1100,
    'iron' => 1700,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1060301)-> #{
    'name' => <<"16489"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 1000,
    'wood' => 1100,
    'iron' => 1700,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1060401)-> #{
    'name' => <<"16491"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 1000,
    'wood' => 1100,
    'iron' => 1700,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 1,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1030101)-> #{
    'name' => <<"16483"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 6000,
    'wood' => 9000,
    'iron' => 5000,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 10,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1040101)-> #{
    'name' => <<"16484"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 10000,
    'wood' => 4000,
    'iron' => 13000,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 11,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1050101)-> #{
    'name' => <<"16486"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 0,
    'wood' => 0,
    'iron' => 0,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 5,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1070101)-> #{
    'name' => <<"14009"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 500,
    'wood' => 1000,
    'iron' => 500,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 6,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1070201)-> #{
    'name' => <<"16494"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 500,
    'wood' => 1000,
    'iron' => 500,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 6,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1080101)-> #{
    'name' => <<"16496"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 2400,
    'wood' => 2000,
    'iron' => 2600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 3,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1080201)-> #{
    'name' => <<"16498"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 2400,
    'wood' => 2000,
    'iron' => 2600,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 3,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1110101)-> #{
    'name' => <<"14828"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 3400,
    'wood' => 2000,
    'iron' => 2200,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 8,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1110201)-> #{
    'name' => <<"16503"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 3400,
    'wood' => 2000,
    'iron' => 2200,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 8,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1130101)-> #{
    'name' => <<"16512"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 100000,
    'wood' => 100000,
    'iron' => 100000,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 27,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1140101)-> #{
    'name' => <<"16514"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 100000,
    'wood' => 100000,
    'iron' => 100000,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 30,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};
get(1150101)-> #{
    'name' => <<"16516"/utf8>>,
    'level' => 1,
    'money' => 0,
    'provisions' => 100000,
    'wood' => 100000,
    'iron' => 100000,
    'time' => 0,
    'building_a_id' => 1010,
    'building_a_num' => 1,
    'building_a_lv' => 30,
    'building_b_id' => 0,
    'building_b_num' => 0,
    'building_b_lv' => 0,
    'building_c_id' => 0,
    'building_c_num' => 0,
    'building_c_lv' => 0,
    'additional_conditions' => 0,
    'additional_conditions_lv' => 0
};

get(_N) -> false.
get_list() ->
	[1010101,1020101,1120101,1120102,1120103,1120301,1120302,1120303,1120401,1120402,1120403,1120201,1120202,1120203,1090101,1060101,1060201,1060301,1060401,1030101,1040101,1050101,1070101,1070201,1080101,1080201,1110101,1110201,1130101,1140101,1150101].
