%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoPublic').
-define('ProtoPublic', true).
-define('ProtoPublic_gb_version', "1.0.0").

-record('ProtoBountyMission',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'task_id'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoBuildingItem',{
    'item_id'	:: integer() | undefined, % = 1, 32 bits
    'num'	:: integer() | undefined, % = 2, 32 bits
    'max_num'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoChapter',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'total_star'	:: integer() | undefined, % = 2, 32 bits
    'star_rewards' = [], % = 3 [#'ProtoPairLong'{}]
    'stage_list' = [] % = 4 [#'ProtoStage'{}]
}).

-record('ProtoFightResult',{
    'combat_id'	:: integer() | undefined, % = 1, 64 bits
    'win_type'	:: integer() | undefined, % = 2, 32 bits
    'l_wastage' = undefined, % = 3 #'ProtoFightWastage'{}
    'r_wastage' = undefined % = 4 #'ProtoFightWastage'{}
}).

-record('ProroBattlefieldReport',{
    'item_list'	:: [integer()] | undefined, % = 1, 32 bits
    'time'	:: integer() | undefined, % = 2, 32 bits
    'player_id'	:: integer() | undefined, % = 3, 64 bits
    'name'	:: iolist() | undefined, % = 4
    'country'	:: integer() | undefined, % = 5, 32 bits
    'type'	:: integer() | undefined, % = 6, 32 bits
    'my_hero_fighter_info' = [], % = 7 [#'ProtoKeyValue'{}]
    'adverse_hero_fighter_info' = [], % = 8 [#'ProtoKeyValue'{}]
    'record_id'	:: integer() | undefined, % = 9, 64 bits
    'is_revenge_success'	:: integer() | undefined % = 10, 32 bits
}).

-record('ProtoRecordID',{
    'tick'	:: integer() | undefined, % = 1, 64 bits
    'id'	:: integer() | undefined, % = 2, 64 bits
    'type'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoStar',{
    'level'	:: integer() | undefined, % = 1, 32 bits
    'experience'	:: integer() | undefined, % = 2, 32 bits
    'inlay_info'	:: [integer()] | undefined % = 3, 32 bits
}).

-record('ProtoMapIndustry',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'earning'	:: integer() | undefined, % = 2, 32 bits
    'time'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoFriend',{
    'show' = undefined, % = 1 #'ProtoShowRole'{}
    'online'	:: integer() | undefined, % = 2, 32 bits
    'offline_tick'	:: integer() | undefined % = 3, 64 bits
}).

-record('ProtoTaskSystem',{
    'main_type'	:: integer() | undefined % = 1, 32 bits
}).

-record('ProtoWinterRank',{
    'no'	:: integer() | undefined, % = 1, 32 bits
    'right'	:: integer() | undefined, % = 2, 32 bits
    'time'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoFight',{
    'phase'	:: integer() | undefined, % = 1, 32 bits
    'round'	:: integer() | undefined, % = 2, 32 bits
    'l_fighter' = undefined, % = 3 #'ProtoFightHero'{}
    'r_fighter' = undefined, % = 4 #'ProtoFightHero'{}
    'process' = [] % = 5 [#'ProtoFightEffect'{}]
}).

-record('ProtoBuilding',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'building_state'	:: integer() | undefined, % = 3, 32 bits
    'is_open'	:: integer() | undefined, % = 4, 32 bits
    'time'	:: integer() | undefined, % = 5, 32 bits
    'total_time'	:: integer() | undefined, % = 6, 32 bits
    'building_info' = undefined, % = 7 #'ProtoBuildingInfo'{}
    'is_can_upgrade'	:: integer() | undefined, % = 8, 32 bits
    'is_mutual'	:: boolean() | 0 | 1 | undefined % = 9
}).

-record('ProtoDungeonedRank',{
    'show' = undefined, % = 1 #'ProtoShowRole'{}
    'kills'	:: integer() | undefined, % = 2, 32 bits
    'tick'	:: integer() | undefined % = 3, 64 bits
}).

-record('ProtoHeroStar',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'inlay_info' = [] % = 2 [#'ProtoStarInlay'{}]
}).

-record('ProtoBuildingInfo',{
    'barrack_train' = undefined, % = 1 #'ProtoEnlistedMan'{}
    'building_item' = undefined, % = 2 #'ProtoBuildingItem'{}
    'equip_tips' = undefined % = 3 #'ProtoKeyValue'{}
}).

-record('ProtoPos',{
    'x'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
    'y'	:: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
}).

-record('ProtoDailyTask',{
    'act_id'	:: integer() | undefined, % = 1, 32 bits
    'task_id'	:: integer() | undefined, % = 2, 32 bits
    'percent'	:: integer() | undefined, % = 3, 32 bits
    'task_info'	:: iolist() | undefined, % = 4
    'task_reward' = [], % = 5 [#'ProtoItemObj'{}]
    'task_exp'	:: integer() | undefined, % = 6, 32 bits
    'hyperlinks'	:: iolist() | undefined % = 7
}).

-record('ProtoCityIndustry',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'hold'	:: integer() | undefined, % = 2, 32 bits
    'add'	:: integer() | undefined, % = 3, 32 bits
    'earning'	:: integer() | undefined, % = 4, 32 bits
    'num'	:: integer() | undefined, % = 5, 32 bits
    'total_num'	:: integer() | undefined, % = 6, 32 bits
    'full_time'	:: integer() | undefined % = 7, 32 bits
}).

-record('ProtoCity',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'build'	:: integer() | undefined, % = 2, 32 bits
    'master' = undefined % = 3 #'ProtoShowRole'{}
}).

-record('ProtoMapClearing',{
    'clearing_id'	:: iolist() | undefined, % = 1
    'type'	:: integer() | undefined, % = 2, 32 bits
    'robot'	:: integer() | undefined, % = 3, 32 bits
    'param'	:: integer() | undefined, % = 4, 32 bits
    'param1'	:: integer() | undefined, % = 5, 64 bits
    'alien_invasion' = undefined % = 6 #'ProtoAlienInvasionInfo'{}
}).

-record('ProtoActivityTID',{
    'server_type'	:: integer() | undefined, % = 1, 32 bits
    'system_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('ProtoScience',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined, % = 3, 32 bits
    'start_tick'	:: integer() | undefined, % = 4, 64 bits
    'accelerate_time'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoFightProcess',{
    'skill_id'	:: integer() | undefined, % = 1, 32 bits
    'object'	:: integer() | undefined, % = 2, 32 bits
    'prefix'	:: iolist() | undefined, % = 3
    'attack_type'	:: integer() | undefined, % = 4, 32 bits
    'effect' = [] % = 5 [#'ProtoFightEffect'{}]
}).

-record('ProtoTroopsHero',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'troops_march'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('ProtoRoleShowInfo',{
    'role_show' = undefined, % = 1 #'ProtoShowRole'{}
    'hero_list' = [] % = 2 [#'ProtoHeroBase'{}]
}).

-record('ProtoEnlistedMan',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'num'	:: integer() | undefined, % = 2, 32 bits
    'max_num'	:: integer() | undefined, % = 3, 32 bits
    'study_time'	:: integer() | undefined, % = 4, 32 bits
    'time'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoTroopsTime',{
    'consume_time'	:: integer() | undefined % = 1, 32 bits
}).

-record('ProtoGenesisChurch',{
    'city'	:: integer() | undefined, % = 1, 32 bits
    'monster'	:: integer() | undefined, % = 2, 32 bits
    'coord'	:: integer() | undefined, % = 3, 32 bits
    'distance'	:: integer() | undefined, % = 4, 32 bits
    'time'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoWashAttribute',{
    'attribute_id'	:: [integer()] | undefined, % = 1, 32 bits
    'wash_attribute_id'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('ProtoHero',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'exp'	:: integer() | undefined, % = 3, 32 bits
    'star'	:: integer() | undefined, % = 4, 32 bits
    'awaken'	:: integer() | undefined, % = 5, 32 bits
    'front_stage'	:: integer() | undefined, % = 6, 32 bits
    'back_stage'	:: integer() | undefined, % = 7, 32 bits
    'front_level'	:: integer() | undefined, % = 8, 32 bits
    'back_level'	:: integer() | undefined, % = 9, 32 bits
    'skill_list'	:: [integer()] | undefined, % = 10, 32 bits
    'skill_learning_list' = [], % = 11 [#'ProtoHeroSkill'{}]
    'skill_learning_number_list' = [], % = 12 [#'ProtoPairLong'{}]
    'honor_title' = undefined, % = 13 #'ProtoPairLong'{}
    'hero_equip' = [], % = 14 [#'ProtoItem'{}]
    'hall_skill_list'	:: [integer()] | undefined, % = 15, 32 bits
    'science_effect_list'	:: [integer()] | undefined, % = 16, 32 bits
    'building_list'	:: [integer()] | undefined, % = 17, 32 bits
    'hero_destiny_list'	:: [integer()] | undefined, % = 18, 32 bits
    'hero_crops_study' = [], % = 19 [#'ProtoKeyValue'{}]
    'hero_star_info' = [], % = 20 [#'ProtoHeroStar'{}]
    'assist' = [], % = 21 [#'ProtoHeroAssist'{}]
    'formation_list' = [] % = 22 [#'ProtoHeroFormation'{}]
}).

-record('ProtoActivity',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'server_type'	:: integer() | undefined, % = 2, 32 bits
    'system_type'	:: integer() | undefined, % = 3, 32 bits
    'main_type'	:: integer() | undefined, % = 4, 32 bits
    'sub_type'	:: integer() | undefined, % = 5, 32 bits
    'start_tick'	:: integer() | undefined, % = 6, 64 bits
    'end_tick'	:: integer() | undefined, % = 7, 64 bits
    'conf_index'	:: integer() | undefined, % = 8, 32 bits
    'time'	:: integer() | undefined, % = 9, 64 bits
    'tips_type'	:: integer() | undefined, % = 10, 32 bits
    'tips'	:: integer() | undefined % = 11, 32 bits
}).

-record('ProtoMarsSuitGrade',{
    'index'	:: integer() | undefined, % = 1, 32 bits
    'state'	:: integer() | undefined, % = 2, 32 bits
    'recharge_number'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoAlienInvasionInfo',{
    'combat'	:: integer() | undefined, % = 1, 64 bits
    'num'	:: integer() | undefined, % = 2, 32 bits
    'conf'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoRank',{
    'rank'	:: integer() | undefined, % = 1, 32 bits
    'value'	:: integer() | undefined, % = 2, 32 bits
    'player_show' = undefined, % = 3 #'ProtoShowRole'{}
    'rank_tick'	:: integer() | undefined % = 4, 64 bits
}).

-record('ProtoHeroCropsStudy',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'empirical'	:: integer() | undefined, % = 3, 32 bits
    'is_break'	:: integer() | undefined, % = 4, 32 bits
    'fail_time'	:: integer() | undefined, % = 5, 32 bits
    'study_time'	:: integer() | undefined, % = 6, 32 bits
    'time'	:: integer() | undefined % = 7, 32 bits
}).

-record('ProtoFightSelf',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'hero' = undefined, % = 2 #'ProtoHeroBase'{}
    'index'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoHeroEquip',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'hero_id'	:: integer() | undefined, % = 2, 32 bits
    'level'	:: integer() | undefined, % = 3, 32 bits
    'break_lvl'	:: integer() | undefined, % = 4, 32 bits
    'up'	:: integer() | undefined, % = 5, 32 bits
    'up_fail'	:: integer() | undefined, % = 6, 32 bits
    'attribute'	:: [integer()] | undefined % = 7, 32 bits
}).

-record('ProtoArenaPlayer',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'is_robot'	:: boolean() | 0 | 1 | undefined, % = 2
    'show' = undefined, % = 3 #'ProtoShowRole'{}
    'hero_list' = [], % = 4 [#'ProtoHeroBase'{}]
    'rank'	:: integer() | undefined, % = 5, 32 bits
    'force'	:: integer() | undefined % = 6, 64 bits
}).

-record('ProtoTriggerType',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'value1'	:: integer() | undefined, % = 2, 32 bits
    'value2'	:: integer() | undefined, % = 3, 32 bits
    'value3'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoGovernmentDetail',{
    'use_times'	:: integer() | undefined, % = 1, 32 bits
    'total_times'	:: integer() | undefined, % = 2, 32 bits
    'use_buy_times'	:: integer() | undefined, % = 3, 32 bits
    'next_refresh_tick'	:: integer() | undefined, % = 4, 64 bits
    'use_free_times'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoBackAct',{
    'act_index'	:: integer() | undefined, % = 1, 32 bits
    'is_open'	:: integer() | undefined, % = 2, 32 bits
    'start_tick'	:: integer() | undefined, % = 3, 64 bits
    'end_tick'	:: integer() | undefined, % = 4, 64 bits
    'disappear_tick'	:: integer() | undefined, % = 5, 64 bits
    'main_type'	:: integer() | undefined, % = 6, 32 bits
    'main_icon'	:: iolist() | undefined, % = 7
    'sub_icon'	:: iolist() | undefined, % = 8
    'open_win'	:: iolist() | undefined, % = 9
    'sort'	:: integer() | undefined, % = 10, 32 bits
    'title'	:: iolist() | undefined, % = 11
    'content'	:: iolist() | undefined % = 12
}).

-record('ProtoMutual',{
    'proto_show_role' = undefined, % = 1 #'ProtoShowRole'{}
    'building_id'	:: integer() | undefined, % = 2, 32 bits
    'building_lv'	:: integer() | undefined, % = 3, 32 bits
    'mutual_times'	:: integer() | undefined, % = 4, 32 bits
    'mutual_total_times'	:: integer() | undefined, % = 5, 32 bits
    'is_mutual'	:: boolean() | 0 | 1 | undefined % = 6
}).

-record('ProtoAlienDetail',{
    'floor'	:: integer() | undefined, % = 1, 32 bits
    'open_state'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined, % = 3, 32 bits
    'buff_list'	:: [integer()] | undefined, % = 4, 32 bits
    'buff_refresh_tick'	:: integer() | undefined, % = 5, 32 bits
    'robot_id'	:: integer() | undefined, % = 6, 32 bits
    'hero_id'	:: integer() | undefined, % = 7, 32 bits
    'start_fight_time'	:: integer() | undefined, % = 8, 32 bits
    'fighters' = [], % = 9 [#'ProtoFightHero'{}]
    'convene_time'	:: integer() | undefined, % = 10, 32 bits
    'force'	:: integer() | undefined % = 11, 32 bits
}).

-record('ProtoHeroBase',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'star'	:: integer() | undefined, % = 3, 32 bits
    'awaken'	:: integer() | undefined, % = 4, 32 bits
    'front_level'	:: integer() | undefined, % = 5, 32 bits
    'back_level'	:: integer() | undefined, % = 6, 32 bits
    'front_stage'	:: integer() | undefined, % = 7, 32 bits
    'back_stage'	:: integer() | undefined, % = 8, 32 bits
    'force'	:: integer() | undefined, % = 9, 64 bits
    'honor_title' = undefined, % = 10 #'ProtoPairLong'{}
    'hero_equip' = [], % = 11 [#'ProtoItem'{}]
    'skill_list'	:: [integer()] | undefined, % = 12, 32 bits
    'hero_base_id'	:: integer() | undefined % = 13, 32 bits
}).

-record('ProtoCountryTask',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'current'	:: integer() | undefined, % = 2, 32 bits
    'target'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoFieldFightEffect',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'trigger' = undefined, % = 2 #'ProtoTriggerType'{}
    'skill_id'	:: integer() | undefined, % = 3, 32 bits
    'player'	:: integer() | undefined, % = 4, 64 bits
    'hero'	:: integer() | undefined, % = 5, 32 bits
    'prefix'	:: iolist() | undefined, % = 6
    'target_player'	:: integer() | undefined, % = 7, 32 bits
    'target_hero'	:: integer() | undefined, % = 8, 32 bits
    'target_prefix'	:: iolist() | undefined, % = 9
    'effect_type'	:: integer() | undefined, % = 10, 32 bits
    'value'	:: integer() | undefined, % = 11, 32 bits
    'extra_value'	:: integer() | undefined, % = 12, 32 bits
    'value_list'	:: integer() | undefined, % = 13, 32 bits
    'attack_type'	:: integer() | undefined, % = 14, 32 bits
    'attack_type_list'	:: integer() | undefined, % = 15, 32 bits
    'hero_list'	:: [integer()] | undefined % = 16, 32 bits
}).

-record('ProtoFightHero',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'name'	:: iolist() | undefined, % = 2
    'is_robot'	:: boolean() | 0 | 1 | undefined, % = 3
    'robot_base_id'	:: integer() | undefined, % = 4, 32 bits
    'win_times'	:: integer() | undefined, % = 5, 32 bits
    'country'	:: integer() | undefined, % = 6, 32 bits
    'office'	:: integer() | undefined, % = 7, 32 bits
    'honor_title'	:: integer() | undefined, % = 8, 32 bits
    'formation'	:: integer() | undefined, % = 9, 32 bits
    'four_d'	:: [integer()] | undefined, % = 10, 32 bits
    'former' = undefined, % = 11 #'ProtoArmyBase'{}
    'latter' = undefined, % = 12 #'ProtoArmyBase'{}
    'hero_base' = undefined, % = 13 #'ProtoHeroBase'{}
    'hero_win_time'	:: integer() | undefined % = 14, 32 bits
}).

-record('ProtoShowRole',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'name'	:: iolist() | undefined, % = 2
    'country'	:: integer() | undefined, % = 3, 32 bits
    'level'	:: integer() | undefined, % = 4, 32 bits
    'vip'	:: integer() | undefined, % = 5, 32 bits
    'force'	:: integer() | undefined, % = 6, 32 bits
    'area'	:: iolist() | undefined, % = 7
    'market'	:: integer() | undefined, % = 8, 32 bits
    'agent_code'	:: integer() | undefined, % = 9, 32 bits
    'server_flag'	:: iolist() | undefined, % = 10
    'server_name'	:: iolist() | undefined, % = 11
    'server_prev'	:: iolist() | undefined, % = 12
    'league_id'	:: integer() | undefined, % = 13, 32 bits
    'league_name'	:: iolist() | undefined, % = 14
    'league_position'	:: integer() | undefined, % = 15, 32 bits
    'head_icon'	:: integer() | undefined, % = 16, 32 bits
    'value'	:: integer() | undefined, % = 17, 32 bits
    'sex'	:: integer() | undefined, % = 18, 32 bits
    'country_pos'	:: integer() | undefined, % = 19, 32 bits
    'city_id'	:: integer() | undefined, % = 20, 32 bits
    'nobility'	:: integer() | undefined, % = 21, 32 bits
    'chat_type'	:: integer() | undefined, % = 22, 32 bits
    'is_robot'	:: boolean() | 0 | 1 | undefined % = 23
}).

-record('ProtoTroopsMarch',{
    'index'	:: integer() | undefined, % = 1, 32 bits
    'city_id'	:: integer() | undefined, % = 2, 32 bits
    'city_list'	:: [integer()] | undefined, % = 3, 32 bits
    'time_list'	:: [integer()] | undefined, % = 4, 32 bits
    'remaining_time'	:: integer() | undefined, % = 5, 32 bits
    'all_time'	:: integer() | undefined % = 6, 32 bits
}).

-record('ProtoFightHighest',{
    'max_dominate' = undefined, % = 1 #'ProtoShowRole'{}
    'max_force' = undefined, % = 2 #'ProtoShowRole'{}
    'max_office' = undefined % = 3 #'ProtoShowRole'{}
}).

-record('ProtoOnlineGift',{
    'gift_id'	:: integer() | undefined, % = 1, 32 bits
    'gift_receive_state'	:: integer() | undefined % = 2, 32 bits
}).

-record('ProtoHeroFormation',{
    'level'	:: integer() | undefined, % = 1, 32 bits
    'class'	:: integer() | undefined, % = 2, 32 bits
    'is_use'	:: boolean() | 0 | 1 | undefined % = 3
}).

-record('ProtoHolySpiritHall',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'grade'	:: integer() | undefined, % = 3, 32 bits
    'work_list' = [], % = 4 [#'ProtoHeroGarde'{}]
    'type_list' = [] % = 5 [#'ProtoKeyValue'{}]
}).

-record('ProtoProp',{
    'name'	:: iolist() | undefined, % = 1
    'value'	:: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
}).

-record('ProtoShop',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'buy_times'	:: integer() | undefined, % = 2, 32 bits
    'refresh_times'	:: integer() | undefined, % = 3, 32 bits
    'grid_list' = [] % = 4 [#'ProtoShopGrid'{}]
}).

-record('ProtoCountryOrder',{
    'country_id'	:: integer() | undefined, % = 1, 32 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'is_open'	:: boolean() | 0 | 1 | undefined, % = 3
    'start_tick'	:: integer() | undefined, % = 4, 64 bits
    'city_id'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoCountryPlayer',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'show' = undefined, % = 2 #'ProtoShowRole'{}
    'country_id'	:: integer() | undefined, % = 3, 32 bits
    'pos_name_id'	:: integer() | undefined, % = 4, 32 bits
    'city_id'	:: integer() | undefined, % = 5, 32 bits
    'can_appoint_master'	:: boolean() | 0 | 1 | undefined, % = 6
    'hero' = undefined % = 7 #'ProtoHeroBase'{}
}).

-record('ProtoMail',{
    'mail_id'	:: integer() | undefined, % = 1, 64 bits
    'mail_type'	:: integer() | undefined, % = 2, 32 bits
    'title'	:: iolist() | undefined, % = 3
    'content'	:: iolist() | undefined, % = 4
    'send_tick'	:: integer() | undefined, % = 5, 64 bits
    'sender_id'	:: integer() | undefined, % = 6, 64 bits
    'sender_name'	:: iolist() | undefined, % = 7
    'overtime_tick'	:: integer() | undefined, % = 8, 64 bits
    'has_read'	:: integer() | undefined, % = 9, 32 bits
    'has_attach'	:: integer() | undefined, % = 10, 32 bits
    'item_list' = [], % = 11 [#'ProtoItem'{}]
    'mail_font'	:: integer() | undefined, % = 12, 32 bits
    'args' = [], % = 13 [#'ProtoMailArg'{}]
    'title_args' = [] % = 14 [#'ProtoMailArg'{}]
}).

-record('ProtoBroadRole',{
    'role_id'	:: integer() | undefined, % = 1, 64 bits
    'role_name'	:: iolist() | undefined % = 2
}).

-record('ProtoOpenServerTask',{
    'task_id'	:: integer() | undefined, % = 1, 32 bits
    'state'	:: integer() | undefined, % = 2, 32 bits
    'grade'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoFightRank',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'country'	:: integer() | undefined, % = 2, 32 bits
    'name'	:: iolist() | undefined, % = 3
    'kills'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoReport',{
    'left_show' = undefined, % = 1 #'ProtoShowRole'{}
    'right_show' = undefined, % = 2 #'ProtoShowRole'{}
    'tick'	:: integer() | undefined, % = 3, 64 bits
    'winner'	:: integer() | undefined, % = 4, 32 bits
    'award_info'	:: [integer()] | undefined, % = 5, 32 bits
    'info1'	:: integer() | undefined, % = 6, 64 bits
    'info2'	:: integer() | undefined % = 7, 64 bits
}).

-record('ProtoItem',{
    'index'	:: integer() | undefined, % = 1, 32 bits
    'unique_id'	:: integer() | undefined, % = 2, 64 bits
    'id'	:: integer() | undefined, % = 3, 32 bits
    'amount'	:: integer() | undefined, % = 4, 32 bits
    'bind'	:: integer() | undefined, % = 5, 32 bits
    'opt_tick'	:: integer() | undefined, % = 6, 64 bits
    'overdue'	:: integer() | undefined, % = 7, 32 bits
    'remove_tick'	:: integer() | undefined, % = 8, 32 bits
    'equip_info' = undefined, % = 9 #'ProtoHeroEquip'{}
    'honor_title' = undefined, % = 10 #'ProtoHonorTitle'{}
    'star_info' = undefined % = 11 #'ProtoStar'{}
}).

-record('ProtoBackActReward',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'cond_float'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
    'cond_int'	:: integer() | undefined, % = 3, 32 bits
    'state'	:: integer() | undefined, % = 4, 32 bits
    'item_list' = [] % = 5 [#'ProtoItem'{}]
}).

-record('ProtoAccRechargeGrade',{
    'index'	:: integer() | undefined, % = 1, 32 bits
    'recharge_number'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoCityBuilding',{
    'building_id'	:: integer() | undefined, % = 1, 32 bits
    'count'	:: integer() | undefined, % = 2, 32 bits
    'lock'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoTroopsNotice',{
    'troops_id'	:: integer() | undefined, % = 1, 64 bits
    'player_id'	:: integer() | undefined, % = 2, 64 bits
    'hero_id'	:: integer() | undefined, % = 3, 32 bits
    'city_list'	:: [integer()] | undefined, % = 4, 32 bits
    'remaining_time'	:: integer() | undefined, % = 5, 32 bits
    'all_time'	:: integer() | undefined, % = 6, 32 bits
    'total_time'	:: [integer()] | undefined % = 7, 32 bits
}).

-record('ProtoSpringMission',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'hero_condition'	:: integer() | undefined, % = 2, 32 bits
    'target_city'	:: integer() | undefined, % = 3, 32 bits
    'award'	:: integer() | undefined, % = 4, 32 bits
    'is_completed'	:: boolean() | 0 | 1 | undefined, % = 5
    'is_received'	:: boolean() | 0 | 1 | undefined, % = 6
    'is_display'	:: boolean() | 0 | 1 | undefined, % = 7
    'is_forward'	:: boolean() | 0 | 1 | undefined, % = 8
    'hero_id'	:: integer() | undefined % = 9, 32 bits
}).

-record('ProtoMailArg',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'int_number'	:: integer() | undefined, % = 2, 64 bits
    'double_number'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
    'str'	:: iolist() | undefined, % = 4
    'role' = undefined, % = 5 #'ProtoShowRole'{}
    'item' = undefined % = 6 #'ProtoItemObj'{}
}).

-record('ProtoCityVisiting',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'hero'	:: integer() | undefined, % = 2, 32 bits
    'num'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoTroops',{
    'troops_id'	:: integer() | undefined, % = 1, 64 bits
    'hero_id'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined, % = 3, 32 bits
    'index'	:: integer() | undefined, % = 4, 32 bits
    'city_id'	:: integer() | undefined, % = 5, 32 bits
    'qian_jun_total'	:: integer() | undefined, % = 6, 32 bits
    'qian_jun'	:: integer() | undefined, % = 7, 32 bits
    'hou_jun_total'	:: integer() | undefined, % = 8, 32 bits
    'hou_jun'	:: integer() | undefined, % = 9, 32 bits
    'qian_jun_all'	:: integer() | undefined, % = 10, 32 bits
    'hou_jun_all'	:: integer() | undefined, % = 11, 32 bits
    'fight'	:: integer() | undefined, % = 12, 32 bits
    'march' = undefined % = 13 #'ProtoTroopsMarch'{}
}).

-record('ProtoCampfire',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'is_recharging'	:: boolean() | 0 | 1 | undefined, % = 2
    'is_received'	:: boolean() | 0 | 1 | undefined, % = 3
    'received_times'	:: integer() | undefined, % = 4, 32 bits
    'total_times'	:: integer() | undefined, % = 5, 32 bits
    'award'	:: [integer()] | undefined, % = 6, 32 bits
    'remain_time'	:: integer() | undefined % = 7, 32 bits
}).

-record('ProtoHeroBusy',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'city_id'	:: integer() | undefined, % = 2, 32 bits
    'param'	:: integer() | undefined, % = 3, 32 bits
    'incident'	:: integer() | undefined, % = 4, 32 bits
    'type'	:: integer() | undefined, % = 5, 32 bits
    'remaining_time'	:: integer() | undefined % = 6, 32 bits
}).

-record('ProtoFightEffect',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'skill_id'	:: integer() | undefined, % = 2, 32 bits
    'flag'	:: integer() | undefined, % = 3, 32 bits
    'object'	:: integer() | undefined, % = 4, 32 bits
    'prefix'	:: iolist() | undefined, % = 5
    'target_object'	:: integer() | undefined, % = 6, 32 bits
    'target_prefix'	:: [iolist()] | undefined, % = 7
    'effect_type'	:: integer() | undefined, % = 8, 32 bits
    'value'	:: integer() | undefined, % = 9, 32 bits
    'extra_value'	:: integer() | undefined, % = 10, 32 bits
    'value_list'	:: [integer()] | undefined, % = 11, 32 bits
    'attack_type'	:: integer() | undefined, % = 12, 32 bits
    'condition'	:: integer() | undefined, % = 13, 32 bits
    'condition_value'	:: integer() | undefined, % = 14, 32 bits
    'condition_str'	:: iolist() | undefined, % = 15
    'attack_type_list'	:: [integer()] | undefined, % = 16, 32 bits
    'former_troops'	:: integer() | undefined, % = 17, 32 bits
    'latter_troops'	:: integer() | undefined, % = 18, 32 bits
    'hero_list'	:: [integer()] | undefined % = 19, 32 bits
}).

-record('ProtoFightDrop',{
    'role_id'	:: integer() | undefined, % = 1, 64 bits
    'detail_map' = [] % = 2 [#'ProtoKeyValue'{}]
}).

-record('ProtoFightWastage',{
    'fighter' = undefined, % = 1 #'ProtoFightHero'{}
    'kills'	:: integer() | undefined, % = 2, 32 bits
    'start_front'	:: integer() | undefined, % = 3, 32 bits
    'start_back'	:: integer() | undefined, % = 4, 32 bits
    'over_front'	:: integer() | undefined, % = 5, 32 bits
    'over_back'	:: integer() | undefined % = 6, 32 bits
}).

-record('ProtoRanker',{
    'rank'	:: integer() | undefined, % = 1, 32 bits
    'value'	:: integer() | undefined, % = 2, 32 bits
    'update_tick'	:: integer() | undefined, % = 3, 32 bits
    'max_force_hero'	:: integer() | undefined, % = 4, 32 bits
    'role_show' = undefined, % = 5 #'ProtoShowRole'{}
    'hero_base' = undefined % = 6 #'ProtoHeroBase'{}
}).

-record('ProtoHeroAssist',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'awaken'	:: integer() | undefined, % = 2, 32 bits
    'star'	:: integer() | undefined, % = 3, 32 bits
    'hero_skill_level'	:: integer() | undefined, % = 4, 32 bits
    'arms_skill_level'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoLeagueMember',{
    'show' = undefined, % = 1 #'ProtoShowRole'{}
    'online'	:: integer() | undefined, % = 2, 32 bits
    'offline_tick'	:: integer() | undefined, % = 3, 64 bits
    'position'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoTroopFight',{
    'fight_info' = undefined, % = 1 #'ProtoFieldFightEffect'{}
    'troop1' = undefined, % = 2 #'ProtoTroop'{}
    'troop2' = undefined % = 3 #'ProtoTroop'{}
}).

-record('ProtoTask',{
    'task_id'	:: integer() | undefined, % = 1, 32 bits
    'task_type'	:: integer() | undefined, % = 2, 32 bits
    'task_flag'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoArmyBase',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'attack'	:: integer() | undefined, % = 3, 32 bits
    'defence'	:: integer() | undefined, % = 4, 32 bits
    'speed'	:: integer() | undefined, % = 5, 32 bits
    'troops'	:: integer() | undefined, % = 6, 32 bits
    'cur_troops'	:: integer() | undefined % = 7, 32 bits
}).

-record('ProtoTopic',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'topic_main'	:: integer() | undefined, % = 2, 32 bits
    'answer_list'	:: [integer()] | undefined, % = 3, 32 bits
    'answered'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoMap',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'country'	:: integer() | undefined, % = 2, 32 bits
    'master'	:: iolist() | undefined, % = 3
    'icon'	:: integer() | undefined, % = 4, 32 bits
    'fighting'	:: integer() | undefined, % = 5, 64 bits
    'guard' = undefined, % = 6 #'ProtoGuard'{}
    'is_open'	:: boolean() | 0 | 1 | undefined, % = 7
    'start_tick'	:: integer() | undefined % = 8, 64 bits
}).

-record('ProtoWelfareExchange',{
    'event_id'	:: integer() | undefined, % = 1, 32 bits
    'time'	:: integer() | undefined, % = 2, 32 bits
    'current_schedule'	:: integer() | undefined, % = 3, 32 bits
    'target_schedule'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoTaskInfo',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'sub_type'	:: integer() | undefined, % = 3, 32 bits
    'status'	:: integer() | undefined, % = 4, 32 bits
    'cond_type'	:: integer() | undefined, % = 5, 32 bits
    'cur_value'	:: integer() | undefined, % = 6, 32 bits
    'final_value'	:: integer() | undefined, % = 7, 32 bits
    'grade'	:: integer() | undefined, % = 8, 32 bits
    'reward_id'	:: integer() | undefined, % = 9, 32 bits
    'cleaning_id'	:: iolist() | undefined, % = 10
    'city_id'	:: integer() | undefined % = 11, 32 bits
}).

-record('ProtoLeagueLog',{
    'log_tick'	:: integer() | undefined, % = 1, 64 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'player_id'	:: integer() | undefined, % = 3, 64 bits
    'player_name'	:: iolist() | undefined, % = 4
    'content'	:: iolist() | undefined % = 5
}).

-record('ProtoIntelligence',{
    'city'	:: integer() | undefined, % = 1, 32 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'time'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoHonourTopReport',{
    'times'	:: integer() | undefined, % = 1, 32 bits
    'report' = [] % = 2 [#'ProtoReport'{}]
}).

-record('ProtoTroopsConsume',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'time'	:: integer() | undefined, % = 2, 32 bits
    'foodstuff'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoDragonPalace',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'expedition_state'	:: integer() | undefined, % = 2, 32 bits
    'is_open'	:: integer() | undefined, % = 3, 32 bits
    'time'	:: integer() | undefined, % = 4, 32 bits
    'is_can_rob'	:: integer() | undefined, % = 5, 32 bits
    'hero_list' = [], % = 6 [#'ProtoHeroBase'{}]
    'item_list' = [], % = 7 [#'ProtoKeyValue'{}]
    'be_rob_num'	:: integer() | undefined, % = 8, 32 bits
    'be_rob_time'	:: [integer()] | undefined % = 9, 32 bits
}).

-record('ProtoWinterFinalRank',{
    'proto_show_role' = undefined, % = 1 #'ProtoShowRole'{}
    'proto_winter_rank' = undefined % = 2 #'ProtoWinterRank'{}
}).

-record('ProtoTroop',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'player_id'	:: integer() | undefined, % = 2, 64 bits
    'country'	:: integer() | undefined, % = 3, 32 bits
    'level'	:: integer() | undefined, % = 4, 32 bits
    'star'	:: integer() | undefined, % = 5, 32 bits
    'force'	:: integer() | undefined, % = 6, 32 bits
    'player_name'	:: iolist() | undefined, % = 7
    'server_flag'	:: iolist() | undefined, % = 8
    'cur_former'	:: integer() | undefined, % = 9, 32 bits
    'tot_former'	:: integer() | undefined, % = 10, 32 bits
    'cur_latter'	:: integer() | undefined, % = 11, 32 bits
    'tot_latter'	:: integer() | undefined, % = 12, 32 bits
    'city_id'	:: integer() | undefined, % = 13, 32 bits
    'state'	:: integer() | undefined, % = 14, 32 bits
    'pos' = undefined, % = 15 #'ProtoPos'{}
    'pos_list' = [], % = 16 [#'ProtoPos'{}]
    'fight' = undefined % = 17 #'ProtoFightEffect'{}
}).

-record('ProtoRechargeDividends',{
    'name'	:: iolist() | undefined, % = 1
    'official_position'	:: integer() | undefined, % = 2, 32 bits
    'is_chatelain'	:: integer() | undefined, % = 3, 32 bits
    'num'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoGateRole',{
    'role_id'	:: integer() | undefined, % = 1, 64 bits
    'name'	:: iolist() | undefined, % = 2
    'level'	:: integer() | undefined, % = 3, 32 bits
    'country'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoStage',{
    'stage_id'	:: integer() | undefined, % = 1, 32 bits
    'is_pass'	:: boolean() | 0 | 1 | undefined, % = 2
    'pass_star'	:: integer() | undefined, % = 3, 32 bits
    'pass_target_list'	:: [boolean()] | 0 | 1 | undefined % = 4
}).

-record('ProtoMoney',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'amount'	:: integer() | undefined % = 2, 32 bits
}).

-record('ProtoCountryRanker',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'show' = undefined, % = 2 #'ProtoShowRole'{}
    'rank_type'	:: integer() | undefined, % = 3, 32 bits
    'rank'	:: integer() | undefined, % = 4, 32 bits
    'value1'	:: integer() | undefined, % = 5, 64 bits
    'value2'	:: integer() | undefined, % = 6, 64 bits
    'is_online'	:: boolean() | 0 | 1 | undefined, % = 7
    'sign_in_tick'	:: integer() | undefined, % = 8, 64 bits
    'sign_out_tick'	:: integer() | undefined, % = 9, 64 bits
    'pos_name_id'	:: integer() | undefined, % = 10, 32 bits
    'city_id'	:: integer() | undefined, % = 11, 32 bits
    'can_appoint_master'	:: boolean() | 0 | 1 | undefined % = 12
}).

-record('ProtoActivityUID',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'server_type'	:: integer() | undefined, % = 2, 32 bits
    'system_type'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoActivityBase',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'main_type'	:: integer() | undefined, % = 2, 32 bits
    'sub_type'	:: integer() | undefined, % = 3, 32 bits
    'group_type'	:: integer() | undefined, % = 4, 32 bits
    'title'	:: iolist() | undefined, % = 5
    'content'	:: iolist() | undefined, % = 6
    'icon'	:: iolist() | undefined, % = 7
    'level_limit'	:: integer() | undefined, % = 8, 32 bits
    'start_tick'	:: integer() | undefined, % = 9, 64 bits
    'end_tick'	:: integer() | undefined, % = 10, 64 bits
    'left_time'	:: integer() | undefined, % = 11, 32 bits
    'sort'	:: integer() | undefined, % = 12, 32 bits
    'extra_value'	:: integer() | undefined % = 13, 64 bits
}).

-record('ProtoChallenge',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'defend_info' = undefined, % = 2 #'ProtoRoleShowInfo'{}
    'attack_num'	:: integer() | undefined, % = 3, 32 bits
    'attack_id'	:: [integer()] | undefined, % = 4, 64 bits
    'attack_buff'	:: [integer()] | undefined, % = 5, 32 bits
    'pond'	:: integer() | undefined, % = 6, 32 bits
    'record_id'	:: integer() | undefined, % = 7, 64 bits
    'hero_troop' = [] % = 8 [#'ProtoHeroTroops'{}]
}).

-record('ProtoGuard',{
    'guard_level'	:: integer() | undefined, % = 1, 32 bits
    'guard_num'	:: integer() | undefined, % = 2, 32 bits
    'defend_num'	:: integer() | undefined, % = 3, 32 bits
    'supplement'	:: integer() | undefined, % = 4, 32 bits
    'dissolve'	:: integer() | undefined, % = 5, 32 bits
    'embrasured'	:: integer() | undefined, % = 6, 32 bits
    'cannon'	:: integer() | undefined, % = 7, 32 bits
    'attack_country'	:: integer() | undefined, % = 8, 32 bits
    'attack_num'	:: integer() | undefined % = 9, 32 bits
}).

-record('ProtoLeague',{
    'id'	:: integer() | undefined, % = 1, 64 bits
    'name'	:: iolist() | undefined, % = 2
    'level'	:: integer() | undefined, % = 3, 32 bits
    'member_amount'	:: integer() | undefined, % = 4, 32 bits
    'max_member'	:: integer() | undefined, % = 5, 32 bits
    'force'	:: integer() | undefined, % = 6, 64 bits
    'rank'	:: integer() | undefined, % = 7, 32 bits
    'has_apply'	:: integer() | undefined % = 8, 32 bits
}).

-record('ProtoArenaRecord',{
    'first_show' = undefined, % = 1 #'ProtoShowRole'{}
    'second_show' = undefined, % = 2 #'ProtoShowRole'{}
    'first_hero_list' = [], % = 3 [#'ProtoHeroBase'{}]
    'second_hero_list' = [], % = 4 [#'ProtoHeroBase'{}]
    'win_type'	:: integer() | undefined, % = 5, 32 bits
    'result_list'	:: [integer()] | undefined, % = 6, 32 bits
    'first_rank'	:: integer() | undefined, % = 7, 32 bits
    'second_rank'	:: integer() | undefined, % = 8, 32 bits
    'tick'	:: integer() | undefined % = 9, 64 bits
}).

-record('ProtoBroadArg',{
    'arg_type'	:: integer() | undefined, % = 1, 32 bits
    'ivalue'	:: integer() | undefined, % = 2, 64 bits
    'dvalue'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
    'strvalue'	:: iolist() | undefined, % = 4
    'role_info' = undefined, % = 5 #'ProtoBroadRole'{}
    'item_info' = undefined, % = 6 #'ProtoItem'{}
    'type'	:: integer() | undefined, % = 7, 32 bits
    'hero_info' = undefined, % = 8 #'ProtoBroadHero'{}
    'hero_skill' = undefined % = 9 #'ProtoHeroSkill'{}
}).

-record('ProtoAlienReward',{
    'item' = undefined, % = 1 #'ProtoItemObj'{}
    'left_tick'	:: integer() | undefined % = 2, 32 bits
}).

-record('ProtoHeroGarde',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'hero_level'	:: integer() | undefined, % = 2, 32 bits
    'star'	:: integer() | undefined, % = 3, 32 bits
    'grade'	:: integer() | undefined, % = 4, 32 bits
    'grade_level'	:: integer() | undefined, % = 5, 32 bits
    'is_battle'	:: integer() | undefined % = 6, 32 bits
}).

-record('ProtoFightDetail',{
    'combat_times'	:: integer() | undefined, % = 1, 32 bits
    'l_size'	:: integer() | undefined, % = 2, 32 bits
    'r_size'	:: integer() | undefined, % = 3, 32 bits
    'l_fighters' = [], % = 4 [#'ProtoFightHero'{}]
    'r_fighters' = [], % = 5 [#'ProtoFightHero'{}]
    'fight' = [], % = 6 [#'ProtoFight'{}]
    'drop_id'	:: integer() | undefined, % = 7, 32 bits
    'win_type'	:: integer() | undefined, % = 8, 32 bits
    'start_tick'	:: integer() | undefined % = 9, 64 bits
}).

-record('ProtoStarInlay',{
    'inlay_type'	:: integer() | undefined, % = 1, 32 bits
    'info'	:: [integer()] | undefined % = 2, 64 bits
}).

-record('ProtoTroopsDetail',{
    'name'	:: iolist() | undefined, % = 1
    'num'	:: integer() | undefined, % = 2, 32 bits
    'soldier'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoHonourTop',{
    'player' = undefined, % = 1 #'ProtoShowRole'{}
    'win'	:: integer() | undefined, % = 2, 32 bits
    'lose'	:: integer() | undefined, % = 3, 32 bits
    'rank'	:: integer() | undefined, % = 4, 32 bits
    'odds'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
    'money'	:: integer() | undefined, % = 6, 32 bits
    'hero_id'	:: integer() | undefined % = 7, 32 bits
}).

-record('ProtoHeroTroops',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'all_troop'	:: integer() | undefined, % = 2, 32 bits
    'now_troop'	:: integer() | undefined % = 3, 32 bits
}).

-record('ProtoAutumnMission',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'industry'	:: integer() | undefined, % = 2, 32 bits
    'industry_level'	:: integer() | undefined, % = 3, 32 bits
    'robber'	:: integer() | undefined, % = 4, 32 bits
    'is_forward'	:: boolean() | 0 | 1 | undefined, % = 5
    'is_display'	:: boolean() | 0 | 1 | undefined, % = 6
    'is_received'	:: boolean() | 0 | 1 | undefined, % = 7
    'last_time'	:: integer() | undefined, % = 8, 32 bits
    'award'	:: [integer()] | undefined, % = 9, 32 bits
    'is_completed'	:: boolean() | 0 | 1 | undefined % = 10
}).

-record('ProtoHeroSkill',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'level'	:: integer() | undefined, % = 2, 32 bits
    'is_active'	:: boolean() | 0 | 1 | undefined, % = 3
    'active_level'	:: integer() | undefined, % = 4, 32 bits
    'is_fixed'	:: boolean() | 0 | 1 | undefined % = 5
}).

-record('ProtoChatList',{
    'chat_type'	:: integer() | undefined, % = 1, 32 bits
    'content_type'	:: integer() | undefined, % = 2, 32 bits
    'wcontent'	:: iolist() | undefined, % = 3
    'voice_sec'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
    'voice_id'	:: integer() | undefined, % = 5, 32 bits
    'show' = undefined, % = 6 #'ProtoShowRole'{}
    'private_show' = undefined, % = 7 #'ProtoShowRole'{}
    'send_tick'	:: integer() | undefined, % = 8, 64 bits
    'addit_list' = [], % = 9 [#'ProtoItem'{}]
    'shout_id'	:: integer() | undefined, % = 10, 32 bits
    'broad_args' = [] % = 11 [#'ProtoBroadArg'{}]
}).

-record('ProtoPairLong',{
    'key'	:: integer() | undefined, % = 1, 64 bits
    'value'	:: integer() | undefined % = 2, 64 bits
}).

-record('ProtoRecharge',{
    'recharge_id'	:: integer() | undefined, % = 1, 32 bits
    'buy_time'	:: integer() | undefined, % = 2, 32 bits
    'refresh_tick'	:: integer() | undefined, % = 3, 64 bits
    'total_by_time'	:: integer() | undefined, % = 4, 32 bits
    'get_time'	:: integer() | undefined % = 5, 32 bits
}).

-record('ProtoOpenServerRank',{
    'rank'	:: integer() | undefined, % = 1, 32 bits
    'tick'	:: integer() | undefined, % = 2, 32 bits
    'player_info' = undefined, % = 3 #'ProtoShowRole'{}
    'grade'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoHonorTitle',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'rand_prop'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('ProtoItemObj',{
    'item_id'	:: integer() | undefined, % = 1, 32 bits
    'amount'	:: integer() | undefined, % = 2, 32 bits
    'effect'	:: integer() | undefined, % = 3, 32 bits
    'flag'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoKeyValue',{
    'key'	:: integer() | undefined, % = 1, 32 bits
    'value'	:: integer() | undefined % = 2, 32 bits
}).

-record('ProtoShopGrid',{
    'id'	:: integer() | undefined, % = 1, 32 bits
    'buy_times'	:: integer() | undefined, % = 2, 32 bits
    'is_open'	:: boolean() | 0 | 1 | undefined, % = 3
    'goods_id'	:: integer() | undefined % = 4, 32 bits
}).

-record('ProtoHeroSkillLike',{
    'skill_id'	:: integer() | undefined, % = 1, 32 bits
    'like_num'	:: integer() | undefined, % = 2, 32 bits
    'is_like'	:: boolean() | 0 | 1 | undefined % = 3
}).

-record('ProtoBroadHero',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'hero_id'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
