%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10107').
-define('ProtoClient_10107', true).
-define('ProtoClient_10107_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10107001',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10107002',{
    'friend_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10107003',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'apply_list'	:: [integer()] | undefined % = 2, 64 bits
}).

-record('Proto10107004',{
    'id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto10107005',{
    'id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto10107006',{
    'id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto10107007',{
    'name'	:: iolist() | undefined % = 1
}).

-record('Proto50107001',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'friend_list' = [] % = 2 [#'ProtoFriend'{}]
}).

-record('Proto50107007',{
    'friend' = undefined % = 1 #'ProtoFriend'{}
}).

-record('Proto80107008',{
    'player_id'	:: integer() | undefined % = 1, 64 bits
}).

-endif.
