%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10119').
-define('ProtoClient_10119', true).
-define('ProtoClient_10119_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10119001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50119001',{
    'function_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto80119001',{
    'function_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto80119002',{
    'function_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto80119003',{
    'function_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-endif.
