%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10112').
-define('ProtoClient_10112', true).
-define('ProtoClient_10112_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto50112001',{
    'vip_level'	:: integer() | undefined, % = 1, 32 bits
    'recharge_money'	:: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
}).

-endif.
