%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10129').
-define('ProtoClient_10129', true).
-define('ProtoClient_10129_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10129001',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'hero_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10129002',{
    'hero_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto80129003',{
    'overdue_list' = [] % = 1 [#'ProtoItem'{}]
}).

-endif.
