%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10101').
-define('ProtoClient_10101', true).
-define('ProtoClient_10101_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto80101001',{
    'show' = undefined, % = 1 #'ProtoShowRole'{}
    'exp'	:: integer() | undefined, % = 2, 32 bits
    'open_days'	:: integer() | undefined, % = 3, 32 bits
    'create_days'	:: integer() | undefined, % = 4, 32 bits
    'create_tick'	:: integer() | undefined % = 5, 64 bits
}).

-endif.
