%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10115').
-define('ProtoClient_10115', true).
-define('ProtoClient_10115_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10115002',{
    'gift_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50115001',{
    'gift_id'	:: integer() | undefined, % = 1, 32 bits
    'surplus_time'	:: integer() | undefined, % = 2, 32 bits
    'is_double'	:: integer() | undefined, % = 3, 32 bits
    'is_get_all'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto80115003',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'is_get_all'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
