%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10133').
-define('ProtoClient_10133', true).
-define('ProtoClient_10133_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10133001',{
    'city_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10133003',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'city_id'	:: integer() | undefined, % = 2, 32 bits
    'building_id'	:: integer() | undefined, % = 3, 32 bits
    'choose'	:: integer() | undefined, % = 4, 32 bits
    'type'	:: integer() | undefined % = 5, 32 bits
}).

-record('Proto50133001',{
    'building' = [], % = 1 [#'ProtoCityBuilding'{}]
    'add1'	:: integer() | undefined, % = 2, 32 bits
    'add2'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50133003',{
    'building_id'	:: integer() | undefined, % = 1, 32 bits
    'value'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
