%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10113').
-define('ProtoClient_10113', true).
-define('ProtoClient_10113_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10113001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10113002',{
    'chapter_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10113003',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'stage_id'	:: integer() | undefined, % = 3, 32 bits
    'hero_list'	:: [integer()] | undefined % = 4, 32 bits
}).

-record('Proto10113004',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10113005',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10113006',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'stage_id'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto10113007',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10113008',{
    'id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50113001',{
    'chapter_list' = [] % = 1 [#'ProtoPairLong'{}]
}).

-record('Proto50113002',{
    'chapter' = undefined, % = 1 #'ProtoChapter'{}
    'used_times'	:: integer() | undefined, % = 2, 32 bits
    'buy_times'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50113003',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'stage_id'	:: integer() | undefined, % = 3, 32 bits
    'hero_list'	:: [integer()] | undefined, % = 4, 32 bits
    'challenge_times'	:: integer() | undefined % = 5, 32 bits
}).

-record('Proto50113004',{
    'buy_times'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50113005',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50113006',{
    'chapter_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'stage_id'	:: integer() | undefined, % = 3, 32 bits
    'challenge_times'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50113007',{
    'chapter_list' = [] % = 1 [#'ProtoChapter'{}]
}).

-record('Proto50113008',{
    'hero_list' = [] % = 1 [#'ProtoHeroBase'{}]
}).

-endif.
