%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10104').
-define('ProtoClient_10104', true).
-define('ProtoClient_10104_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10104003',{
    'mail_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10104004',{
    'mail_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10104005',{
    'mail_id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto50104002',{
    'mail_list' = [] % = 1 [#'ProtoMail'{}]
}).

-record('Proto50104003',{
    'mail_info' = undefined % = 1 #'ProtoMail'{}
}).

-record('Proto50104004',{
    'mail_list' = [] % = 1 [#'ProtoMail'{}]
}).

-record('Proto50104005',{
    'mail_id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto80104001',{
    'mail_id_list'	:: [integer()] | undefined % = 1, 64 bits
}).

-endif.
