%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10153').
-define('ProtoClient_10153', true).
-define('ProtoClient_10153_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10153001',{
    'code'	:: iolist() | undefined % = 1
}).

-endif.
