%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10130').
-define('ProtoClient_10130', true).
-define('ProtoClient_10130_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10130002',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'use_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50130001',{
    'remaining_free_times'	:: integer() | undefined, % = 1, 32 bits
    'all_times'	:: integer() | undefined, % = 2, 32 bits
    'buy_times' = [] % = 3 [#'ProtoKeyValue'{}]
}).

-record('Proto50130002',{
    'remaining_free_times'	:: integer() | undefined, % = 1, 32 bits
    'all_times'	:: integer() | undefined, % = 2, 32 bits
    'buy_times' = [], % = 3 [#'ProtoKeyValue'{}]
    'is_cruel'	:: integer() | undefined, % = 4, 32 bits
    'item' = [] % = 5 [#'ProtoItem'{}]
}).

-endif.
