%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10144').
-define('ProtoClient_10144', true).
-define('ProtoClient_10144_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10144001',{
    'shop_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10144002',{
    'shop_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'grid_id'	:: integer() | undefined, % = 3, 32 bits
    'goods_id'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto10144003',{
    'shop_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10144004',{
    'prop_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50144001',{
    'shop' = undefined % = 1 #'ProtoShop'{}
}).

-record('Proto50144002',{
    'shop_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'grid_id'	:: integer() | undefined, % = 3, 32 bits
    'goods_id'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50144003',{
    'shop_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50144004',{
    'num_limit'	:: integer() | undefined % = 1, 32 bits
}).

-endif.
