%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10110').
-define('ProtoClient_10110', true).
-define('ProtoClient_10110_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto80110002',{
    'recharge_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto80110003',{
    'recharge_info' = [], % = 1 [#'ProtoRecharge'{}]
    'have_first'	:: integer() | undefined, % = 2, 32 bits
    'get_first'	:: integer() | undefined % = 3, 32 bits
}).

-endif.
