%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10140').
-define('ProtoClient_10140', true).
-define('ProtoClient_10140_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10140003',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'hero_list'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('Proto10140004',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'hero_list'	:: [integer()] | undefined, % = 3, 32 bits
    'is_revenge'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto10140006',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'player_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10140007',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10140008',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50140001',{
    'info' = [], % = 1 [#'ProtoDragonPalace'{}]
    'rob_player_id'	:: integer() | undefined, % = 2, 32 bits
    'astrology'	:: integer() | undefined, % = 3, 32 bits
    'rob_times'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50140002',{
    'hero_list' = [] % = 1 [#'ProtoKeyValue'{}]
}).

-record('Proto50140004',{
    'is_win'	:: integer() | undefined, % = 1, 32 bits
    'star'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50140005',{
    'rob_info' = [], % = 1 [#'ProroBattlefieldReport'{}]
    'be_rob_info' = [] % = 2 [#'ProroBattlefieldReport'{}]
}).

-record('Proto50140006',{
    'info' = [], % = 1 [#'ProtoDragonPalace'{}]
    'player_info' = undefined % = 2 #'ProtoShowRole'{}
}).

-record('Proto50140007',{
    'id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto80140009',{
    'info' = [] % = 1 [#'ProtoDragonPalace'{}]
}).

-endif.
