%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10106').
-define('ProtoClient_10106', true).
-define('ProtoClient_10106_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10106003',{
    'name'	:: iolist() | undefined % = 1
}).

-record('Proto10106004',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'league_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10106005',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'player_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10106007',{
    'member_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10106011',{
    'member_id'	:: integer() | undefined, % = 1, 64 bits
    'position'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10106012',{
    'member_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10106013',{
    'notice'	:: iolist() | undefined % = 1
}).

-record('Proto50106001',{
    'league_list' = [] % = 1 [#'ProtoLeague'{}]
}).

-record('Proto50106002',{
    'league' = undefined, % = 1 #'ProtoLeague'{}
    'notice'	:: iolist() | undefined, % = 2
    'leader_show' = undefined, % = 3 #'ProtoShowRole'{}
    'self_position'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50106010',{
    'member_list' = [] % = 1 [#'ProtoLeagueMember'{}]
}).

-record('Proto50106014',{
    'apply_list' = [] % = 1 [#'ProtoLeagueMember'{}]
}).

-record('Proto50106015',{
    'log_list' = [] % = 1 [#'ProtoLeagueLog'{}]
}).

-record('Proto80106009',{
    'league_id'	:: integer() | undefined, % = 1, 64 bits
    'league_name'	:: iolist() | undefined, % = 2
    'league_level'	:: integer() | undefined, % = 3, 32 bits
    'league_position'	:: integer() | undefined % = 4, 32 bits
}).

-endif.
