%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10147').
-define('ProtoClient_10147', true).
-define('ProtoClient_10147_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10147001',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50147001',{
    'city'	:: integer() | undefined % = 1, 32 bits
}).

-endif.
