%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10141').
-define('ProtoClient_10141', true).
-define('ProtoClient_10141_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10141001',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'hero_id'	:: integer() | undefined, % = 2, 32 bits
    'type'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50141002',{
    'city_visiting' = [] % = 1 [#'ProtoCityVisiting'{}]
}).

-record('Proto80141002',{
    'city_visiting' = undefined % = 1 #'ProtoCityVisiting'{}
}).

-endif.
