%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10154').
-define('ProtoClient_10154', true).
-define('ProtoClient_10154_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10154001',{
    'block_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto80154002',{
    'troop_list' = [] % = 1 [#'ProtoTroop'{}]
}).

-record('Proto80154003',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'hero_id'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
