%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10118').
-define('ProtoClient_10118', true).
-define('ProtoClient_10118_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10118002',{
    'task_id'	:: integer() | undefined, % = 1, 32 bits
    'task_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10118003',{
    'guidance_info' = undefined % = 1 #'ProtoPairLong'{}
}).

-record('Proto50118001',{
    'task_info' = [] % = 1 [#'ProtoTask'{}]
}).

-record('Proto50118002',{
    'task_id'	:: integer() | undefined, % = 1, 32 bits
    'task_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50118005',{
    'bounty_mission_list' = [] % = 1 [#'ProtoBountyMission'{}]
}).

-record('Proto80118001',{
    'task_info' = [] % = 1 [#'ProtoTask'{}]
}).

-record('Proto80118002',{
    'guidance_info' = [] % = 1 [#'ProtoPairLong'{}]
}).

-record('Proto80118005',{
    'bounty_mission' = undefined, % = 1 #'ProtoBountyMission'{}
    'state'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
