%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10111').
-define('ProtoClient_10111', true).
-define('ProtoClient_10111_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10111002',{
    'player_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10111003',{
    'name'	:: iolist() | undefined % = 1
}).

-record('Proto10111004',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'hero_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10111999',{
    'cmd_name'	:: iolist() | undefined, % = 1
    'param1'	:: integer() | undefined, % = 2, 64 bits
    'param2'	:: integer() | undefined, % = 3, 64 bits
    'param3'	:: integer() | undefined, % = 4, 64 bits
    'param4'	:: integer() | undefined % = 5, 64 bits
}).

-record('Proto50111002',{
    'show' = undefined % = 1 #'ProtoRoleShowInfo'{}
}).

-record('Proto50111003',{
    'name'	:: iolist() | undefined, % = 1
    'value'	:: integer() | undefined, % = 2, 32 bits
    'cool_time'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50111004',{
    'hero_base' = undefined % = 1 #'ProtoHeroBase'{}
}).

-record('Proto80111001',{
    'prop_list' = [], % = 1 [#'ProtoProp'{}]
    'force'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto80111999',{
    'str'	:: iolist() | undefined % = 1
}).

-endif.
