%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10109').
-define('ProtoClient_10109', true).
-define('ProtoClient_10109_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10109001',{
    'rank_type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10109002',{
    'country'	:: integer() | undefined, % = 1, 32 bits
    'rank_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50109001',{
    'rank_type'	:: integer() | undefined, % = 1, 32 bits
    'rank_list' = [], % = 2 [#'ProtoRank'{}]
    'self_rank' = undefined % = 3 #'ProtoRank'{}
}).

-record('Proto50109002',{
    'rank_list' = [], % = 1 [#'ProtoRanker'{}]
    'self_rank' = undefined, % = 2 #'ProtoRanker'{}
    'country'	:: integer() | undefined, % = 3, 32 bits
    'rank_type'	:: integer() | undefined % = 4, 32 bits
}).

-endif.
