%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10120').
-define('ProtoClient_10120', true).
-define('ProtoClient_10120_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10120002',{
    'head_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50120001',{
    'info' = [] % = 1 [#'ProtoPairLong'{}]
}).

-record('Proto50120002',{
    'head_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto80120003',{
    'head_id'	:: integer() | undefined % = 1, 32 bits
}).

-endif.
