%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10117').
-define('ProtoClient_10117', true).
-define('ProtoClient_10117_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10117001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10117002',{
    'act_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10117010',{
    'act_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10117011',{
    'act_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10117012',{
    'act_id'	:: integer() | undefined, % = 1, 32 bits
    'task_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50117001',{
    'act_list' = [] % = 1 [#'ProtoActivityBase'{}]
}).

-record('Proto50117002',{
    'act_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto50117010',{
    'info' = [] % = 1 [#'ProtoDailyTask'{}]
}).

-record('Proto80117001',{
    'act_list' = [] % = 1 [#'ProtoActivityBase'{}]
}).

-record('Proto80117002',{
    'act_list' = [] % = 1 [#'ProtoActivityBase'{}]
}).

-record('Proto80117003',{
    'act_list' = [] % = 1 [#'ProtoActivityBase'{}]
}).

-endif.
