%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10134').
-define('ProtoClient_10134', true).
-define('ProtoClient_10134_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10134001',{
    'hero_list'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto50134005',{
    'rank_list' = [], % = 1 [#'ProtoDungeonedRank'{}]
    'self' = undefined, % = 2 #'ProtoShowRole'{}
    'self_kills'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto80134003',{
    'state'	:: integer() | undefined, % = 1, 32 bits
    'combat_id'	:: integer() | undefined, % = 2, 64 bits
    'cur_floor'	:: integer() | undefined, % = 3, 32 bits
    'use_times'	:: integer() | undefined, % = 4, 32 bits
    'buy_times'	:: integer() | undefined, % = 5, 32 bits
    'former_type'	:: integer() | undefined, % = 6, 32 bits
    'latter_type'	:: integer() | undefined % = 7, 32 bits
}).

-endif.
