%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10100').
-define('ProtoClient_10100', true).
-define('ProtoClient_10100_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10100001',{
    'account'	:: iolist() | undefined, % = 1
    'tick'	:: iolist() | undefined, % = 2
    'session'	:: iolist() | undefined, % = 3
    'server_flag'	:: iolist() | undefined, % = 4
    'server_name'	:: iolist() | undefined, % = 5
    'agent'	:: iolist() | undefined, % = 6
    'market'	:: integer() | undefined, % = 7, 32 bits
    'net_type'	:: iolist() | undefined, % = 8
    'sys_version'	:: iolist() | undefined, % = 9
    'sys_model'	:: iolist() | undefined, % = 10
    'mac'	:: iolist() | undefined, % = 11
    'client_type'	:: integer() | undefined, % = 12, 32 bits
    'area'	:: iolist() | undefined, % = 13
    'sdk_sid'	:: iolist() | undefined, % = 14
    'msg_tocken'	:: iolist() | undefined, % = 15
    'device'	:: iolist() | undefined % = 16
}).

-record('Proto10100002',{
    'sex'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10100003',{
    'role_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10100004',{
    'country'	:: integer() | undefined, % = 1, 32 bits
    'name'	:: iolist() | undefined, % = 2
    'sex'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto10100007',{
    'role_id'	:: integer() | undefined, % = 1, 64 bits
    'session'	:: iolist() | undefined % = 2
}).

-record('Proto10100099',{
    'test12'	:: integer() | undefined, % = 1, 32 bits
    'df4er4489972'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50100001',{
    'role_list' = [] % = 1 [#'ProtoGateRole'{}]
}).

-record('Proto50100002',{
    'name'	:: iolist() | undefined % = 1
}).

-record('Proto50100004',{
    'role_id'	:: integer() | undefined, % = 1, 64 bits
    'role_name'	:: iolist() | undefined % = 2
}).

-record('Proto50100005',{
    'time'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto50100006',{
    'info' = [] % = 1 [#'ProtoPairLong'{}]
}).

-record('Proto50100008',{
    'tick'	:: integer() | undefined, % = 1, 64 bits
    'val'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
