%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10126').
-define('ProtoClient_10126', true).
-define('ProtoClient_10126_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10126005',{
    'unique_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10126010',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'flag'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50126017',{
    'flag'	:: boolean() | 0 | 1 | undefined % = 1
}).

-record('Proto10126016',{
    'bin_id'	:: integer() | undefined, % = 1, 32 bits
    'index'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10126011',{
    'unique_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto50126015',{
    'make_list' = [] % = 1 [#'ProtoKeyValue'{}]
}).

-record('Proto10126012',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'flag'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50126001',{
    'equip' = [] % = 1 [#'ProtoHeroEquip'{}]
}).

-record('Proto50126010',{
    'lock'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto10126014',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'index'	:: integer() | undefined, % = 2, 32 bits
    'flag'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50126012',{
    'attribute_id'	:: [integer()] | undefined, % = 1, 32 bits
    'wash_attribute_id'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('Proto50126009',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'flag'	:: integer() | undefined, % = 2, 32 bits
    'unique_id'	:: integer() | undefined, % = 3, 64 bits
    'item_list' = [] % = 4 [#'ProtoItemObj'{}]
}).

-record('Proto10126001',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10126003',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'unique_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10126018',{
    'unique_id'	:: [integer()] | undefined % = 1, 64 bits
}).

-record('Proto50126016',{
    'flag'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10126006',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50126006',{
    'flag'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50126008',{
    'time'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50126007',{
    'attribute_id'	:: [integer()] | undefined, % = 1, 32 bits
    'lock'	:: [integer()] | undefined, % = 2, 32 bits
    'wash_attribute_id'	:: [integer()] | undefined, % = 3, 32 bits
    'gold_finger'	:: [integer()] | undefined % = 4, 32 bits
}).

-record('Proto80126002',{
    'hero_equip' = [], % = 1 [#'ProtoHeroEquip'{}]
    'suit'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50126014',{
    'attribute_id'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto10126017',{
    'unique_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto50126005',{
    'flag'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50126002',{
    'unique_id_list'	:: [integer()] | undefined, % = 1, 64 bits
    'suit'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10126007',{
    'unique_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10126013',{
    'unique_id'	:: integer() | undefined, % = 1, 64 bits
    'index'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10126004',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'unique_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10126009',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10126008',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'unique_id'	:: integer() | undefined, % = 2, 64 bits
    'num'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50126011',{
    'wash_attribute_id'	:: [integer()] | undefined % = 1, 32 bits
}).

-record('Proto50126013',{
    'gold_finger'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10126002',{
    'hero_id'	:: integer() | undefined % = 1, 32 bits
}).

-endif.
