%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10124').
-define('ProtoClient_10124', true).
-define('ProtoClient_10124_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10124002',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'item_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50124001',{
    'residue_degree'	:: integer() | undefined, % = 1, 32 bits
    'sum_degree'	:: integer() | undefined, % = 2, 32 bits
    'time_to_special'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto50124002',{
    'item_list' = [], % = 1 [#'ProtoItemObj'{}]
    'type'	:: integer() | undefined, % = 2, 32 bits
    'surplus_time'	:: integer() | undefined, % = 3, 32 bits
    'sum_degree'	:: integer() | undefined, % = 4, 32 bits
    'time_to_special'	:: integer() | undefined % = 5, 32 bits
}).

-endif.
