%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10123').
-define('ProtoClient_10123', true).
-define('ProtoClient_10123_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10123003',{
    'building_id'	:: integer() | undefined, % = 1, 32 bits
    'use'	:: integer() | undefined, % = 2, 32 bits
    'num'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto10123004',{
    'building_id'	:: integer() | undefined, % = 1, 32 bits
    'use'	:: integer() | undefined, % = 2, 32 bits
    'item_id'	:: integer() | undefined, % = 3, 32 bits
    'num'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto10123005',{
    'class_id_big'	:: integer() | undefined, % = 1, 32 bits
    'class_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10123007',{
    'building_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10123008',{
    'building_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10123009',{
    'building_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10123010',{
    'skip'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10123011',{
    'mutual' = undefined % = 1 #'ProtoMutual'{}
}).

-record('Proto10123012',{
    'mutual' = undefined % = 1 #'ProtoMutual'{}
}).

-record('Proto10123013',{
    'mutual' = undefined % = 1 #'ProtoMutual'{}
}).

-record('Proto10123014',{
    'do_it'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50123001',{
    'building_list' = [], % = 1 [#'ProtoBuilding'{}]
    'workers_num'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50123003',{
    'building' = undefined % = 1 #'ProtoBuilding'{}
}).

-record('Proto50123004',{
    'building' = undefined % = 1 #'ProtoBuilding'{}
}).

-record('Proto50123007',{
    'building' = undefined % = 1 #'ProtoBuilding'{}
}).

-record('Proto50123008',{
    'info' = undefined, % = 1 #'ProtoBuilding'{}
    'workers_num'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50123009',{
    'mutual_list' = [], % = 1 [#'ProtoMutual'{}]
    'building' = undefined % = 2 #'ProtoBuilding'{}
}).

-record('Proto50123010',{
    'mutual_list' = [], % = 1 [#'ProtoMutual'{}]
    'my_mutual_list' = [] % = 2 [#'ProtoMutual'{}]
}).

-record('Proto50123011',{
    'mutual_list' = [] % = 1 [#'ProtoMutual'{}]
}).

-record('Proto50123012',{
    'mutual_list' = [] % = 1 [#'ProtoMutual'{}]
}).

-record('Proto50123013',{
    'mutual_list' = [] % = 1 [#'ProtoMutual'{}]
}).

-record('Proto50123014',{
    'mutual_list' = [] % = 1 [#'ProtoMutual'{}]
}).

-record('Proto80123002',{
    'building_list' = [], % = 1 [#'ProtoBuilding'{}]
    'workers_num'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto80123006',{
    'building_list' = [] % = 1 [#'ProtoBuilding'{}]
}).

-record('Proto80123009',{
    'mutual_list' = [] % = 1 [#'ProtoMutual'{}]
}).

-endif.
