%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10138').
-define('ProtoClient_10138', true).
-define('ProtoClient_10138_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10138001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10138003',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'type'	:: integer() | undefined, % = 2, 32 bits
    'num'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto10138004',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'state'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50138001',{
    'hero_busy_list' = [] % = 1 [#'ProtoHeroBusy'{}]
}).

-record('Proto50138003',{
    'hero_id'	:: integer() | undefined, % = 1, 32 bits
    'total_time'	:: integer() | undefined, % = 2, 32 bits
    'remaining_time'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto80138001',{
    'state'	:: integer() | undefined, % = 1, 32 bits
    'hero_busy_list' = [] % = 2 [#'ProtoHeroBusy'{}]
}).

-endif.
