%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10146').
-define('ProtoClient_10146', true).
-define('ProtoClient_10146_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10146001',{
    'city_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10146002',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'is_free'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10146003',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'city_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10146004',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'hero_id'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10146005',{
    'city_id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50146001',{
    'city_id'	:: integer() | undefined, % = 1, 32 bits
    'robot_id'	:: integer() | undefined, % = 2, 32 bits
    'times'	:: integer() | undefined, % = 3, 32 bits
    'left_times'	:: integer() | undefined, % = 4, 32 bits
    'is_lock'	:: integer() | undefined, % = 5, 32 bits
    'refresh_time_tick'	:: integer() | undefined, % = 6, 64 bits
    'is_max_free_refresh_times'	:: boolean() | 0 | 1 | undefined, % = 7
    'item_list' = [], % = 8 [#'ProtoItem'{}]
    'predict' = [], % = 9 [#'ProtoKeyValue'{}]
    'hero_base' = undefined % = 10 #'ProtoHeroBase'{}
}).

-record('Proto80146001',{
    'puppet_list' = [] % = 1 [#'ProtoKeyValue'{}]
}).

-endif.
