%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10137').
-define('ProtoClient_10137', true).
-define('ProtoClient_10137_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10137001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10137002',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'hero_list'	:: [integer()] | undefined, % = 2, 32 bits
    'index'	:: integer() | undefined, % = 3, 32 bits
    'tag_id'	:: integer() | undefined, % = 4, 64 bits
    'tag_rank'	:: integer() | undefined % = 5, 32 bits
}).

-record('Proto10137003',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10137004',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10137005',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10137006',{
    'page'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10137007',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50137001',{
    'country_top' = [], % = 1 [#'ProtoArenaPlayer'{}]
    'challenge_list' = [], % = 2 [#'ProtoArenaPlayer'{}]
    'self_rank'	:: integer() | undefined, % = 3, 32 bits
    'buy_times'	:: integer() | undefined, % = 4, 32 bits
    'used_times'	:: integer() | undefined, % = 5, 32 bits
    'self' = undefined % = 6 #'ProtoArenaPlayer'{}
}).

-record('Proto50137002',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'hero_list'	:: [integer()] | undefined, % = 2, 32 bits
    'index'	:: integer() | undefined, % = 3, 32 bits
    'tag_id'	:: integer() | undefined, % = 4, 64 bits
    'tag_rank'	:: integer() | undefined % = 5, 32 bits
}).

-record('Proto50137003',{
    'buy_times'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50137004',{
    'player_list' = [] % = 1 [#'ProtoArenaPlayer'{}]
}).

-record('Proto50137005',{
    'record_list' = [] % = 1 [#'ProtoArenaRecord'{}]
}).

-record('Proto50137006',{
    'page'	:: integer() | undefined, % = 1, 32 bits
    'max_page'	:: integer() | undefined, % = 2, 32 bits
    'rank_list' = [], % = 3 [#'ProtoArenaPlayer'{}]
    'self_rank'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50137007',{
    'buy_times'	:: integer() | undefined, % = 1, 32 bits
    'used_times'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
