%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10103').
-define('ProtoClient_10103', true).
-define('ProtoClient_10103_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10103001',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10103003',{
    'pack_type'	:: integer() | undefined, % = 1, 32 bits
    'unique_id'	:: integer() | undefined, % = 2, 64 bits
    'amount'	:: integer() | undefined, % = 3, 32 bits
    'use_argv'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto80103002',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'max_size'	:: integer() | undefined, % = 2, 32 bits
    'item_list' = [] % = 3 [#'ProtoItem'{}]
}).

-record('Proto80103004',{
    'money_list' = [] % = 1 [#'ProtoMoney'{}]
}).

-record('Proto80103005',{
    'item_list' = [], % = 1 [#'ProtoItem'{}]
    'tips_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto80103006',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'item_list' = [] % = 2 [#'ProtoItem'{}]
}).

-record('Proto80103007',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'item_list' = [] % = 2 [#'ProtoItem'{}]
}).

-record('Proto80103008',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'item_list' = [] % = 2 [#'ProtoItem'{}]
}).

-endif.
