%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10145').
-define('ProtoClient_10145', true).
-define('ProtoClient_10145_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10145002',{
    'type'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10145004',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'hero_list'	:: [integer()] | undefined % = 2, 32 bits
}).

-record('Proto10145005',{
    'challenge_type'	:: integer() | undefined, % = 1, 32 bits
    'report_type'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10145007',{
    'buy_time'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10145009',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'challenge_function'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50145001',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'choose_type'	:: integer() | undefined, % = 2, 32 bits
    'challenge_info' = [], % = 3 [#'ProtoChallenge'{}]
    'stage'	:: integer() | undefined, % = 4, 32 bits
    'timer'	:: integer() | undefined, % = 5, 32 bits
    'challenge_time'	:: integer() | undefined, % = 6, 32 bits
    'recover_time'	:: integer() | undefined, % = 7, 32 bits
    'buy_time'	:: integer() | undefined, % = 8, 32 bits
    'hero_num'	:: integer() | undefined, % = 9, 32 bits
    'activity_type'	:: integer() | undefined % = 10, 32 bits
}).

-record('Proto50145005',{
    'report_info' = [], % = 1 [#'ProtoReport'{}]
    'challenge_type'	:: integer() | undefined, % = 2, 32 bits
    'report_type'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto80145006',{
    'challenge_info' = [], % = 1 [#'ProtoChallenge'{}]
    'type'	:: integer() | undefined, % = 2, 32 bits
    'choose_type'	:: integer() | undefined, % = 3, 32 bits
    'stage'	:: integer() | undefined, % = 4, 32 bits
    'timer'	:: integer() | undefined, % = 5, 32 bits
    'challenge_time'	:: integer() | undefined, % = 6, 32 bits
    'recover_time'	:: integer() | undefined, % = 7, 32 bits
    'buy_time'	:: integer() | undefined % = 8, 32 bits
}).

-record('Proto80145008',{
    'is_open'	:: integer() | undefined, % = 1, 32 bits
    'time'	:: integer() | undefined, % = 2, 32 bits
    'type'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto80145010',{
    'report' = undefined, % = 1 #'ProtoReport'{}
    'challenge_type'	:: integer() | undefined % = 2, 32 bits
}).

-endif.
