%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10150').
-define('ProtoClient_10150', true).
-define('ProtoClient_10150_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10150001',{
    'other'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto10150101',{
    'uid' = undefined % = 1 #'ProtoActivityUID'{}
}).

-record('Proto10150102',{
    'uid' = undefined, % = 1 #'ProtoActivityUID'{}
    'grade'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10150103',{
    'uid' = undefined % = 1 #'ProtoActivityUID'{}
}).

-record('Proto10150104',{
    'uid' = undefined, % = 1 #'ProtoActivityUID'{}
    'award'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10150105',{
    'uid' = undefined % = 1 #'ProtoActivityUID'{}
}).

-record('Proto50150001',{
    'tid' = undefined, % = 1 #'ProtoActivityTID'{}
    'act_list' = [] % = 2 [#'ProtoActivity'{}]
}).

-record('Proto50150101',{
    'act' = undefined, % = 1 #'ProtoActivity'{}
    'acc'	:: integer() | undefined, % = 2, 32 bits
    'grade_list' = [] % = 3 [#'ProtoAccRechargeGrade'{}]
}).

-record('Proto50150102',{
    'uid' = undefined, % = 1 #'ProtoActivityUID'{}
    'grade'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50150103',{
    'act' = undefined, % = 1 #'ProtoActivity'{}
    'today_acc'	:: integer() | undefined, % = 2, 32 bits
    'state'	:: integer() | undefined, % = 3, 32 bits
    'need_num'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50150104',{
    'uid' = undefined, % = 1 #'ProtoActivityUID'{}
    'award'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50150105',{
    'act' = undefined, % = 1 #'ProtoActivity'{}
    'acc'	:: integer() | undefined, % = 2, 32 bits
    'grade_list' = undefined % = 3 #'ProtoMarsSuitGrade'{}
}).

-record('Proto50150106',{
    'uid' = undefined, % = 1 #'ProtoActivityUID'{}
    'grade'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto80150001',{
    'tid' = undefined, % = 1 #'ProtoActivityTID'{}
    'act_list' = [] % = 2 [#'ProtoActivity'{}]
}).

-record('Proto80150002',{
    'tid' = undefined, % = 1 #'ProtoActivityTID'{}
    'add_list' = [], % = 2 [#'ProtoActivity'{}]
    'del_list' = [] % = 3 [#'ProtoActivity'{}]
}).

-endif.
