%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gb_compile version 1.0.0
-ifndef('ProtoClient_10105').
-define('ProtoClient_10105', true).
-define('ProtoClient_10105_gb_version', "1.0.0").
-include("ProtoPublic.hrl").

-record('Proto10105001',{
    'chat_type'	:: integer() | undefined, % = 1, 32 bits
    'private_role_id'	:: integer() | undefined, % = 2, 64 bits
    'content_type'	:: integer() | undefined, % = 3, 32 bits
    'wcontent'	:: iolist() | undefined, % = 4
    'voice_sec'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
    'vcontent'	:: iodata() | undefined, % = 6
    'addit_list' = [] % = 7 [#'ProtoItem'{}]
}).

-record('Proto10105006',{
    'chat_type'	:: integer() | undefined, % = 1, 32 bits
    'voice_id'	:: integer() | undefined, % = 2, 64 bits
    'private_role_id'	:: integer() | undefined % = 3, 64 bits
}).

-record('Proto10105009',{
    'state'	:: integer() | undefined, % = 1, 32 bits
    'player_id'	:: integer() | undefined % = 2, 64 bits
}).

-record('Proto10105011',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'state'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto10105014',{
    'player_id'	:: integer() | undefined % = 1, 64 bits
}).

-record('Proto10105015',{
    'player_id'	:: integer() | undefined, % = 1, 64 bits
    'state'	:: integer() | undefined % = 2, 32 bits
}).

-record('Proto50105006',{
    'chat_type'	:: integer() | undefined, % = 1, 32 bits
    'voice_id'	:: integer() | undefined, % = 2, 64 bits
    'content'	:: iodata() | undefined, % = 3
    'voice_length'	:: integer() | undefined % = 4, 32 bits
}).

-record('Proto50105008',{
    'chat_list' = [] % = 1 [#'ProtoChatList'{}]
}).

-record('Proto50105011',{
    'id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto50105013',{
    'player_list' = [] % = 1 [#'ProtoShowRole'{}]
}).

-record('Proto50105014',{
    'info' = undefined % = 1 #'ProtoShowRole'{}
}).

-record('Proto50105015',{
    'id'	:: integer() | undefined % = 1, 32 bits
}).

-record('Proto80105002',{
    'chat_type'	:: integer() | undefined, % = 1, 32 bits
    'content_type'	:: integer() | undefined, % = 2, 32 bits
    'wcontent'	:: iolist() | undefined, % = 3
    'voice_sec'	:: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
    'voice_id'	:: integer() | undefined, % = 5, 64 bits
    'show' = undefined, % = 6 #'ProtoShowRole'{}
    'private_show' = undefined, % = 7 #'ProtoShowRole'{}
    'send_tick'	:: integer() | undefined, % = 8, 64 bits
    'addit_list' = [], % = 9 [#'ProtoItem'{}]
    'shout_id'	:: integer() | undefined, % = 10, 32 bits
    'broad_args' = [] % = 11 [#'ProtoBroadArg'{}]
}).

-record('Proto80105003',{
    'type'	:: integer() | undefined, % = 1, 32 bits
    'content'	:: iolist() | undefined, % = 2
    'cast_type'	:: integer() | undefined % = 3, 32 bits
}).

-record('Proto80105004',{
    'shout_id'	:: integer() | undefined, % = 1, 32 bits
    'broad_args' = [] % = 2 [#'ProtoBroadArg'{}]
}).

-record('Proto80105005',{
    'tips'	:: iolist() | undefined % = 1
}).

-record('Proto80105009',{
    'player_id' = [] % = 1 [#'ProtoShowRole'{}]
}).

-record('Proto80105011',{
    'state'	:: integer() | undefined % = 1, 32 bits
}).

-endif.
