{
	[
		'src/util/mod_server.erl'
	],
	[
		debug_info,
		inline,
		warnings_as_errors,
		{i, 'include'},
		{outdir, 'ebin'}
	]
}.
{
	[
		'src/*',
		'src/*/*',
		'src/*/*/*',
		'src/*/*/*/*',
		'src/*/*/*/*/*'
	],
	[
		debug_info,
		inline,
		warnings_as_errors,
		{i, 'include'}, 
		{outdir, 'ebin'}
	]
}.